# Delegation completeness: every computational name upstream exports must resolve.
#
# The shim ports the numeric kernel and overrides the functions it accelerates. Everything else
# *computational* that upstream exports is a verbatim-upstream delegating wrapper (R/delegate.R,
# generated by scripts/gen_delegate.py), so `library(cellchatrs)` resolves the same names as
# `library(CellChat)`. This gate pins that property three ways, in increasing strength:
#
#   1. **Resolution.** Every delegated name exists as a function in the installed namespace. A name
#      dropped from NAMESPACE or deleted from delegate.R fails here, not as a confusing
#      "could not find function" three gates downstream.
#   2. **Delegation, not a stub.** Each body must reference the upstream cache. A wrapper silently
#      replaced by `function(...) NULL` (or by a reimplementation that was never gated) would still
#      resolve, so resolution alone proves nothing about what the name *does*.
#   3. **Spot `identical()` checks** on the zero-dependency pure functions among them: `triMean` and
#      `geometricMean` on fixed vectors, against pinned upstream. These are the only delegated
#      names whose entire contract fits in one call with no object, database, or package needed.
#
# Visualization.R/app.R contents and the plot-returning analysis functions are deliberately absent
# (locked decision 14.1); the exclusion list with reasons is in R/delegate.R's header and is asserted
# here too, so an exclusion silently turning into dead code would fail rather than drift.
#
# Usage: R_LIBS=.rlib R --vanilla -f tests/parity/check_delegation.R
suppressWarnings(suppressMessages(library(cellchatrs)))

fails <- 0L
n_cmp <- 0L
cmp <- function(label, ok, detail = "") {
  n_cmp <<- n_cmp + 1L
  cat(sprintf("%-58s %s%s\n", label, if (ok) "ok" else "MISMATCH",
              if (nzchar(detail)) paste0("  ", detail) else ""))
  if (!ok) fails <<- fails + 1L
  invisible(ok)
}

ns <- asNamespace("cellchatrs")

## ---------------------------------------------------------------- 1. the expected set
## Read from the generator's table, not duplicated here: the single source of truth is
## scripts/gen_delegate.py's DELEGATE dict, and this gate parses the emitted R/delegate.R header
## for nothing -- instead it recomputes the expectation from upstream's NAMESPACE minus the
## exclusion list, so a name added upstream in the pinned tree is noticed rather than silently
## uncovered.
up <- readLines("/scratch/mdra00001/tmp/opencode/CellChat/NAMESPACE")
up <- sub("^export\\((.*)\\)$", "\\1", grep("^export\\(", up, value = TRUE))
up <- unique(unlist(strsplit(up, ","))); up <- trimws(gsub("\"", "", up))
shim <- ls(ns)
missing <- sort(setdiff(up, shim))

## The exclusion prefixes, kept in sync with R/delegate.R's header by construction: both list the
## same locked decision, and a name that stops matching either list shows up as an unexpected
## missing or an unexpected present below.
is_vis <- function(m) {
  for (v in c("netVisual", "plotGeneExpression", "dotPlot", "barPlot", "barplot_internal",
              "pieChart", "spatialDimPlot", "spatialFeaturePlot", "StackedVlnPlot", "scPalette",
              "ggPalette", "colorRamp3", "CellChat_theme_opts", "netAnalysis_signalingRole",
              "netAnalysis_river", "netAnalysis_dot", "netAnalysis_diff",
              "netAnalysis_signalingChanges", "runCellChatApp", "netVisual_")) {
    if (startsWith(m, v)) return(TRUE)
  }
  m %in% c("netAnalysis_contribution", "compareInteractions")
}
unexplained <- missing[!vapply(missing, is_vis, TRUE)]
cmp("every non-visual upstream name resolves in the shim", length(unexplained) == 0L,
    if (length(unexplained)) paste(utils::head(unexplained, 12), collapse = ", ") else
      sprintf("%d upstream names, %d shim names", length(up), length(shim)))

## ---------------------------------------------------------------- 2. delegation, not a stub
## A body that does not mention the upstream cache is either a reimplementation (which belongs in
## the ledger with its own gate) or a stub (which resolves and returns garbage). Both fail here.
delegated <- function(name) {
  f <- get(name, envir = ns)
  if (!is.function(f)) return(paste("not a function:", class(f)))
  src <- paste(deparse(body(f)), collapse = "\n")
  if (!grepl("cellchatrs_upstream_cached|cellchatrs_upstream_", src, fixed = FALSE)) {
    return("body does not reach the pinned upstream")
  }
  TRUE
}
## Only the names R/delegate.R owns are held to this: ported functions legitimately do something
## else, and checking them here would confuse the port gate with the delegation gate.
## Parsed straight from the generator's table, which is the single source of truth: a name added
## to DELEGATE without a wrapper, or a wrapper without a table entry, fails here rather than drifting.
gen <- readLines("scripts/gen_delegate.py")
gen_names <- unique(sub('^\\s*"([A-Za-z][A-Za-z0-9._]*)": \\(".*$', "\\1",
                        grep('": \\("', gen, value = TRUE)))
bad <- list()
for (nm in sort(gen_names)) {
  if (!exists(nm, envir = ns, inherits = FALSE)) {
    bad[[nm]] <- "absent from the installed namespace"
  } else {
    r <- delegated(nm)
    if (!isTRUE(r)) bad[[nm]] <- r
  }
}
cmp("all delegated names reach the pinned upstream", length(bad) == 0L,
    if (length(bad)) paste(sprintf("%s (%s)", names(bad), unlist(bad)), collapse = "; ")
    else sprintf("%d wrappers checked", length(gen_names)))

## ---------------------------------------------------------------- 3. spot identical() checks
## The only delegated names whose whole contract fits in one dependency-free call. Fixed vectors
## with exact answers (0.5 and 4 for triMean/geometricMean are not accidental: they are values whose
## decimal text round-trips, so a formatting-level disagreement cannot hide behind them).
CC <- Sys.getenv("CELLCHAT_SRC", "/scratch/mdra00001/tmp/opencode/CellChat")
UPE <- new.env(parent = globalenv())
for (p in c("Matrix", "collapse", "dplyr", "future", "rlang")) {
  suppressWarnings(suppressMessages(requireNamespace(p, quietly = TRUE)))
}
for (f in c("modeling.R", "analysis.R", "utilities.R", "database.R")) {
  suppressWarnings(suppressMessages(
    sys.source(file.path(CC, "R", f), envir = UPE, keep.source = FALSE)))
}
for (v in list(c(0, 0, 1, 1), c(1, 2, 3, 4), c(0.1, 0.2, 0.3, 1e-300))) {
  cmp(sprintf("triMean identical on [%s]", paste(v, collapse = ",")),
      identical(cellchatrs::triMean(v), UPE$triMean(v)))
}
for (v in list(c(1, 4, 16), c(0.5, 2, 8), c(1, 1, 1))) {
  cmp(sprintf("geometricMean identical on [%s]", paste(v, collapse = ",")),
      identical(cellchatrs::geometricMean(v), UPE$geometricMean(v)))
}
## The bare-name aliases must be the same code path as the documented wrappers, not a second copy
## that can drift: identical bodies, not just identical results.
## `body()` returns the `{ ... }` block, not the call, so the comparison is against the braced
## form. What this pins is stronger than equal results: the two names share one code path, so a fix
## to the wrapper cannot fail to reach the bare name.
cmp("mergeCellChat is the documented wrapper",
    identical(body(cellchatrs::mergeCellChat),
              quote({cellchatrs_upstream_mergeCellChat(...)})))
cmp("createCellChat is the documented wrapper",
    identical(body(cellchatrs::createCellChat),
              quote({cellchatrs_upstream_createCellChat(...)})))

cat(sprintf("\n%s: %d failing comparisons out of %d\n",
            if (fails == 0L) "DELEGATION-COMPLETE" else "MISMATCH", fails, n_cmp))
quit(status = if (fails == 0L) 0L else 1L)
