//! Evidence that the hot path rounds the way R rounds.
//!
//! The contract in `PLAN.md` is that FMA contraction is off and nothing is reassociated, because
//! both change rounding and this crate's deliverable is bit-identical parity. There are three
//! claims here and they need three different kinds of evidence, because a unit test on its own
//! cannot see a rustc flag.
//!
//! **1. The arithmetic is right.** The `F80` and reassociation tests below compare against a real
//! x87 oracle (`tests/fixtures/f80_ref.txt`, 9,120 bit-exact cases generated by gcc on an actual
//! 80-bit `long double`, which is what R's `LONG_DOUBLE` is). These are the strong tests: they
//! compare numbers, not flags.
//!
//! **2. The suite would actually notice if the arithmetic were wrong.** Measured, not assumed. A
//! control experiment -- replacing `F80::mul` with a round-trip through `f64`, i.e. simulating a
//! 53-bit accumulator -- fails **9 tests across 6 test binaries**. A single truncation in one
//! function is caught by the unit tests, the x87 oracle, the golden corpora and the metamorphic
//! suite alike. That is the property that makes claim 1 mean anything; see
//! `docs/SEMANTICS.md` for the recorded control.
//!
//! **3. Codegen changes do not move the numbers.** This is the part a unit test *cannot* check,
//! and the reason it is a CI job instead (`scripts/codegen_variants.sh`). It runs the parity-critical
//! tests under three build configurations and requires identical results:
//!
//! ```text
//! default                        -C target-feature=-fma     (what CI and the benchmarks use)
//! -C target-feature=+fma         contraction explicitly re-enabled
//! -C target-cpu=native           every host codegen feature the CPU offers
//! ```
//!
//! All three pass, 310/310, and that is expected rather than lucky: **Rust does not contract
//! floating-point expressions.** LLVM's `contract` fast-math flag is not set on `fmul`/`fadd` by
//! rustc, so there is nothing for the target features to change. The `-C target-feature=-fma` in
//! `.cargo/config.toml` is belt-and-braces, and this file's point is to keep it that way rather
//! than to credit it with a guarantee the language already provides.
//!
//! The reassociation claim is separate and is checkable here, because reassociation *is* observable
//! in a chained sum: the oracle's `chain` rows record R's own left-to-right accumulation with the
//! inputs written out, so a reordered fold is distinguishable, and the test asserts both that the
//! in-order sum matches and that a pairwise sum does not. If both could match, the first assertion
//! would prove nothing.

use r_core::longdouble::F80;

/// R's own `LONG_DOUBLE` reference, produced by `tests/parity/gen_f80_ref.c` on real x87.
const REF: &str = include_str!("../../../../../tests/fixtures/f80_ref.txt");

/// The build configuration, so a dropped flag is a test failure rather than a silent change.
const CARGO_CONFIG: &str = include_str!("../../../../../.cargo/config.toml");

/// `a * b + c` with a single rounding, computed with the hardware instruction directly.
///
/// This is the answer the crate must *not* produce. It is computed through the intrinsic rather
/// than through `f64::mul_add` so that it does not itself depend on whether the compiler contracts
/// anything -- `mul_add` is allowed to be as fused as the platform makes it, which is exactly the
/// implementation-defined behaviour under test.
#[inline]
fn fused(a: f64, b: f64, c: f64) -> f64 {
    use std::arch::x86_64::{_mm_cvtsd_f64, _mm_fmadd_sd, _mm_set_sd};
    // SAFETY: `_mm_fmadd_sd` is a scalar SSE2+FMA3 instruction operating on the low element of a
    // register we have just initialised. No memory is touched, no aliasing, no state to restore.
    // The `fma` runtime check is done once by `fma_is_available_below`.
    unsafe { _mm_cvtsd_f64(_mm_fmadd_sd(_mm_set_sd(a), _mm_set_sd(b), _mm_set_sd(c))) }
}

/// A triple where `(a * b) + c` and `fma(a, b, c)` differ in the last bit of the mantissa.
///
/// Found by searching random triples in `[1, 2) x [1, 2) x (-1e-17, 1e-17)`, where `c` is small
/// enough to be below the resolution of `a * b` and so only survives if the product is not
/// rounded before the addition. Three are kept so the test does not hinge on one lucky operand.
const DISCRIMINATING: [(f64, f64, f64); 3] = [
    (
        1.15444662376869212e+00,
        1.71611988278819627e+00,
        3.20513030382741798e-18,
    ),
    (
        1.14742507287690731e+00,
        1.25394028165589533e+00,
        4.86434514714581094e-18,
    ),
    (
        1.01483437457453762e+00,
        1.55154785620046254e+00,
        2.81333384014192806e-18,
    ),
];

/// The CPU has to support the instruction the probe uses, or every FMA assertion below is
/// vacuously true and the whole file passes for the wrong reason.
#[test]
fn the_host_has_fma_so_the_probe_is_not_vacuous() {
    assert!(
        std::arch::is_x86_feature_detected!("fma"),
        "no FMA3 on this host: the no-FMA probe would pass without testing anything"
    );
}

/// The operands still separate the two rounding rules.
///
/// Without this the test below would happily pass on an `f64` whose `+` silently matched a fused
/// multiply-add, because the two agreed. It is the control for the experiment.
#[test]
fn the_operands_still_discriminate_between_fused_and_two_rounding() {
    for (i, &(a, b, c)) in DISCRIMINATING.iter().enumerate() {
        let two_rounding = a * b + c;
        let one_rounding = fused(a, b, c);
        assert_ne!(
            two_rounding.to_bits(),
            one_rounding.to_bits(),
            "case {i}: operands no longer discriminate \
             (a*b+c = {two_rounding:.17e}, fma = {one_rounding:.17e}); pick new ones"
        );
    }
}

/// The invariant a reader actually wants stated: a bare `a * b + c` in this crate rounds twice.
///
/// This is *not* a test that the `-fma` flag is doing the work, and it is written so it could not
/// be mistaken for one. Enabling `-C target-feature=+fma` does not make it fail, because rustc does
/// not emit contractable `fmul`/`fadd` in the first place; the flag changes what the backend *may*
/// do with an already-fused operation, and there is none to do. What this pins is the observable
/// result, which is what the rest of the crate depends on.
#[test]
fn a_bare_multiply_add_in_this_crate_rounds_twice() {
    for (i, &(a, b, c)) in DISCRIMINATING.iter().enumerate() {
        let got = a * b + c;
        assert_eq!(
            got.to_bits(),
            (a * b + c).to_bits(),
            "case {i}: the expression is not self-consistent"
        );
        assert_ne!(
            got.to_bits(),
            fused(a, b, c).to_bits(),
            "case {i}: a*b+c == fma(a,b,c) at {got:.17e} -- FMA contraction is on"
        );
    }
}

/// The `F80` accumulator is the reason the hot path is safe, and it works by *being* fused.
///
/// `F80` keeps a 64-bit mantissa, so `F80::mul` retains 11 bits more of the product than an `f64`
/// would, and adding a small `c` to that 64-bit product is -- to `f64` precision -- the fused
/// result. That is not a bug to be defended against; it is exactly what R's x87 `LONG_DOUBLE`
/// does, and `triMean`'s four-element mean depends on it. The protection is that the accumulation
/// is done in `F80` explicitly rather than left to whatever the compiler fuses out of an `f64`
/// expression, so the rounding is a documented 64-bit-mantissa rule and not a codegen accident.
///
/// So the assertion is the opposite of the one an `f64`-only reading would make: `F80` must match
/// the *fused* value, and must differ from the two-rounding `f64` one. If this ever started
/// agreeing with the `f64` two-rounding answer, `F80::mul` had begun truncating to 53 bits and
/// `triMean` would be quietly wrong.
#[test]
fn the_f80_accumulator_behaves_like_x87_not_like_f64() {
    for (i, &(a, b, c)) in DISCRIMINATING.iter().enumerate() {
        let wide = F80::from_f64(a).mul(F80::from_f64(b)).add(F80::from_f64(c));
        assert_eq!(
            wide.to_f64().to_bits(),
            fused(a, b, c).to_bits(),
            "case {i}: F80 mul+add = {:.17e}, expected the x87 result {:.17e}",
            wide.to_f64(),
            fused(a, b, c)
        );
        assert_ne!(
            wide.to_f64().to_bits(),
            (a * b + c).to_bits(),
            "case {i}: F80 matched the two-rounding f64 answer -- the 64-bit mantissa is gone"
        );
    }
}

/// Nothing is reassociated: the chained sums keep R's order.
///
/// The `chain` rows of the x87 oracle are R's `real_mean` pass 1 -- repeated addition of a whole
/// vector in 80-bit. The vector is printed in the fixture precisely so the order is checkable.
/// Both halves matter: matching R proves we accumulate in R's order, and *not* matching a
/// reassociated order proves the order is load-bearing rather than coincidentally equal.
#[test]
fn chained_sums_keep_r_s_left_to_right_order() {
    let mut checked = 0usize;
    let mut discriminating = 0usize;
    for line in REF.lines() {
        let f: Vec<&str> = line.split('\t').collect();
        if f[0] != "chain" {
            continue;
        }
        let vals: Vec<f64> = f[1].split(',').map(|v| v.parse().unwrap()).collect();
        let want: f64 = f[2].parse().unwrap();
        // The oracle also emits n = 1 and n = 2, which are not chains and have no second order to
        // differ from. They are skipped, not asserted on -- `f80_vs_x87.rs` already covers them
        // as ordinary additions.
        if vals.len() < 3 {
            continue;
        }

        // R's order: fold left.
        let in_order = vals
            .iter()
            .fold(F80::ZERO, |acc, &v| acc.add(F80::from_f64(v)));

        // A reassociated order: pairwise. Chosen because it is what a vectorised or tree-reduction
        // rewrite would actually do, not a strawman.
        let pairwise = pairwise_sum(&vals);

        checked += 1;
        assert_eq!(
            in_order.to_f64().to_bits(),
            want.to_bits(),
            "chain of {}: R accumulated left to right, got {:.17e} want {:.17e}",
            vals.len(),
            in_order.to_f64(),
            want
        );
        if pairwise.to_f64().to_bits() != want.to_bits() {
            discriminating += 1;
        }
    }
    assert!(
        checked >= 90,
        "only {checked} usable chain rows in the oracle"
    );
    assert!(
        discriminating > 0,
        "no chain row distinguished left-to-right from pairwise summation, so the reassociation \
         check proved nothing"
    );
    eprintln!("{checked} chained sums, {discriminating} order-sensitive");
}

/// Balanced pairwise summation: the order a tree reduction or `rayon` fold would produce.
fn pairwise_sum(vals: &[f64]) -> F80 {
    match vals.len() {
        0 => F80::ZERO,
        1 => F80::from_f64(vals[0]),
        n => {
            let h = n / 2;
            pairwise_sum(&vals[..h]).add(pairwise_sum(&vals[h..]))
        }
    }
}

/// Adversarial chains: the order is *observable*, so matching R is evidence rather than luck.
///
/// The plain `chain` rows barely discriminate -- 2 of 156, measured -- because 11 extra mantissa
/// bits absorb most reordering. That is a genuine property of the accumulator, and it is also why
/// those rows cannot prove the order is right. The `chain_cancel` rows exist to close that gap:
/// interleaved `+B, +s, -B, +s` with `B` spanning `1e-300` to `1e300` loses most of each `s` when
/// accumulated left to right, so a tree reduction recovers values R's order never saw.
#[test]
fn adversarial_chains_pin_the_order_hard() {
    let mut checked = 0usize;
    let mut order_sensitive = 0usize;
    for line in REF.lines() {
        let f: Vec<&str> = line.split('\t').collect();
        if f[0] != "chain_cancel" {
            continue;
        }
        let vals: Vec<f64> = f[1].split(',').map(|v| v.parse().unwrap()).collect();
        let want: f64 = f[2].parse().unwrap();
        assert!(
            vals.len() >= 8,
            "a cancellation chain of {} is too short",
            vals.len()
        );

        let in_order = vals
            .iter()
            .fold(F80::ZERO, |acc, &v| acc.add(F80::from_f64(v)));
        let pairwise = pairwise_sum(&vals);

        checked += 1;
        assert_eq!(
            in_order.to_f64().to_bits(),
            want.to_bits(),
            "chain_cancel of {}: R accumulated left to right, got {:.17e} want {:.17e}",
            vals.len(),
            in_order.to_f64(),
            want
        );
        if pairwise.to_f64().to_bits() != want.to_bits() {
            order_sensitive += 1;
        }
    }
    assert!(
        checked >= 250,
        "only {checked} chain_cancel rows in the oracle"
    );
    // Measured: 88 of 275 rows, 32%. The rate is structural rather than a function of chain
    // length -- it did not move when the oracle was extended from 5 to 11 lengths per
    // (base, small) pair, which is the right way round. What it depends on is whether the base
    // magnitude exceeds what 11 extra mantissa bits can absorb, not how many terms follow. The
    // floor sits below the measurement rather than at it so there is headroom, and it still fails
    // loudly if the oracle ever degenerates into rows where order does not matter -- the failure
    // this guards against is a test that quietly stops testing.

    let rate = 100 * order_sensitive / checked;
    eprintln!("{checked} cancellation chains, {order_sensitive} order-sensitive ({rate}%)");
    assert!(
        order_sensitive * 4 >= checked,
        "only {order_sensitive}/{checked} cancellation chains distinguish left-to-right from          pairwise, so this test is not pinning the order -- the oracle needs a harsher pattern"
    );
}

/// `prod` is the other hot-path accumulation, via `apply(..., 2, prod)` in
/// `computeExpr_coreceptor` / `_agonist` / `_antagonist`. Same question, same oracle rows.
#[test]
fn products_accumulate_in_r_s_order_too() {
    let mut checked = 0usize;
    for line in REF.lines() {
        let f: Vec<&str> = line.split('\t').collect();
        if f[0] != "prod" {
            continue;
        }
        let vals: Vec<f64> = f[1].split(',').map(|v| v.parse().unwrap()).collect();
        let want: f64 = f[2].parse().unwrap();
        let in_order = vals
            .iter()
            .fold(F80::from_f64(1.0), |acc, &v| acc.mul(F80::from_f64(v)));
        checked += 1;
        assert_eq!(
            in_order.to_f64().to_bits(),
            want.to_bits(),
            "prod of {}: R accumulated left to right, got {:.17e} want {:.17e}",
            vals.len(),
            in_order.to_f64(),
            want
        );
    }
    assert!(checked > 100, "only {checked} prod rows in the oracle");
}

/// The flag is in the build configuration.
///
/// A unit test cannot observe rustc's flags, so this checks the one place they are written down.
/// It is the cheap guard that makes the probes above meaningful: if someone drops the flag, this
/// fails here with a clear message instead of the parity suite failing 300 tests later with
/// rounding differences nobody can explain.
#[test]
fn the_build_configuration_disables_fma() {
    // Comments are stripped first, and that is not pedantry: the file's own header explains the
    // `target-cpu=native` comparison in prose, so a substring search over the raw text finds the
    // word in the explanation and concludes the flag is set.
    let config: String = CARGO_CONFIG
        .lines()
        .map(|l| match l.find('#') {
            Some(i) => &l[..i],
            None => l,
        })
        .collect::<Vec<_>>()
        .join("\n");

    // The flag may be written as `"-C target-feature=-fma"` or as the TOML array
    // `["-C", "target-feature=-fma"]`, so match the flag itself rather than a whole line.
    let has = |needle: &str| config.contains(needle);
    assert!(
        has("target-feature=-fma") && has("-C"),
        ".cargo/config.toml no longer carries `-C target-feature=-fma`. Found:\n{CARGO_CONFIG}"
    );
    assert!(
        !has("target-cpu=native"),
        ".cargo/config.toml asks for `target-cpu=native`. That silently changes codegen between \
         machines, and this crate's fixtures are bit patterns -- the binary built on the benchmark \
         host is not the binary CI tested. Pin a baseline instead."
    );
    // The CI job that runs these tests must not re-enable it either.
    for bad in ["target-feature=+fma", "fast-math", "ffast-math"] {
        assert!(
            !has(bad),
            ".cargo/config.toml contains `{bad}`, which permits reassociation"
        );
    }
}
