//! Parity for `computeRegionDistance` against the frozen corpus in
//! `tests/fixtures/region_golden.txt` (generated by `tests/parity/gen_region_golden.R`).
//!
//! # What this suite does and does not pin
//!
//! It pins the **arithmetic**: the trimmed mean, the `min.cells`-style threshold tests in
//! upstream's order, the `unique`/`intersect` counts against `k.min` and `k.min.contact`, the
//! per-sample merge with its two different means, the `> 0` binarisation of a fraction, the
//! `adj * t(adj)` symmetrisation against `(d + t(d)) / 2` on `d.spatial`, the `== 0 -> NaN`
//! step, and the `NaN` left behind by a level that is absent from the data. All of that is
//! deterministic and the corpus is a valid oracle for it, because the generator runs upstream's
//! body verbatim with only the neighbour *query* replaced.
//!
//! It deliberately does **not** pin the neighbour query against upstream. `Annoy` is randomised
//! and approximate, so upstream is not an oracle there; that is why the exact k-d tree is
//! justified at all. The generator only substitutes a neighbour query when the fixture's
//! recorded margin shows the nearest neighbour beats its runner-up by at least
//! `MIN_MARGIN`. `the_recorded_margins_hold_up` re-checks that here, so a later edit to a layout
//! that quietly destroys the property fails in Rust too and not only in the generator.
//!
//! Doubles are compared by bit pattern. The corpus is R's `format(digits = 17)`, which round-trips
//! a double exactly, and `NaN` is compared as "is NaN" because the corpus cannot distinguish
//! payloads.

use r_core::spatial::{region_distance, RegionError, RegionInput};
use std::collections::HashMap;

#[derive(Debug, Default, Clone)]
struct Case {
    n: usize,
    d: usize,
    group_levels: Vec<String>,
    group_index: Vec<usize>,
    samples_levels: Vec<String>,
    sample_index: Vec<usize>,
    coords: Vec<f64>,
    interaction_range: Option<f64>,
    contact_range: Option<f64>,
    contact_knn_k: Option<usize>,
    ratio: Vec<f64>,
    tol: Vec<f64>,
    k_min: usize,
    contact_dependent: bool,
    do_symmetric: bool,
    /// `d1 / d2`: the worst nearest-neighbour ambiguity in the layout, `<= 1 / MIN_MARGIN`.
    margin: f64,
    error: Option<String>,
    want_d_spatial: Vec<f64>,
    want_adj_contact: Vec<f64>,
    want_dimnames: Vec<String>,
}

/// The same, for a record that carries a 1-based row index in field 2, so the values start at
/// field 3. Reading from field 2 would silently prepend the row number as a value.
fn vec_f64_at(f: &[&str], start: usize) -> Vec<f64> {
    f[start..].iter().copied().map(num).collect()
}

fn vec_usize(f: &[&str]) -> Vec<usize> {
    f[2..].iter().map(|x| num(x) as usize).collect()
}

fn num(s: &str) -> f64 {
    match s {
        "<NaN>" | "NaN" | "<NA>" | "NA" => f64::NAN,
        "Inf" => f64::INFINITY,
        "-Inf" => f64::NEG_INFINITY,
        other => other.parse().expect("a corpus number must parse"),
    }
}

/// Parse one corpus field that may be the explicit "absent" marker.
fn opt_f64(s: &str) -> Option<f64> {
    if s == "-" {
        None
    } else {
        Some(s.parse().expect("an optional corpus number must parse"))
    }
}

fn load() -> (Vec<String>, HashMap<String, Case>) {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../../tests/fixtures/region_golden.txt");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let mut order: Vec<String> = Vec::new();
    let mut cases: HashMap<String, Case> = HashMap::new();
    let mut cur;
    for line in text.lines() {
        let f: Vec<&str> = line.split('\t').collect();
        match f[0] {
            "n_cases" => {}
            "case" => {
                cur = f[1].to_string();
                order.push(cur.clone());
                cases.insert(cur.clone(), Case::default());
            }
            // name, nrow, ncol, group levels, nlevels(group), nsamples, k.min, contact.dependent
            "meta" => {
                let c = cases.get_mut(f[1]).unwrap();
                c.n = f[2].parse().unwrap();
                c.d = f[3].parse().unwrap();
                c.group_levels = f[4].split(',').map(str::to_string).collect();
                let nlev: usize = f[5].parse().unwrap();
                assert_eq!(
                    nlev,
                    c.group_levels.len(),
                    "{}: nlevels(group) disagrees with the level list",
                    f[1]
                );
                c.samples_levels = (0..f[6].parse::<usize>().unwrap())
                    .map(|i| format!("s{}", i + 1))
                    .collect();
                c.k_min = f[7].parse().unwrap();
                c.contact_dependent = f[8] == "TRUE";
            }
            "opt" => {
                let c = cases.get_mut(f[1]).unwrap();
                c.interaction_range = opt_f64(f[2]);
                c.contact_range = opt_f64(f[3]);
                c.contact_knn_k = if f[4] == "-" {
                    None
                } else {
                    Some(f[4].parse().unwrap())
                };
            }
            "flags" => cases.get_mut(f[1]).unwrap().do_symmetric = f[2] == "TRUE",
            "ratio" => {
                let v: Vec<f64> = f[2].split(',').map(|x| x.parse().unwrap()).collect();
                cases.get_mut(f[1]).unwrap().ratio = v;
            }
            "tol" => {
                let v: Vec<f64> = f[2].split(',').map(|x| x.parse().unwrap()).collect();
                cases.get_mut(f[1]).unwrap().tol = v;
            }
            "margin" => cases.get_mut(f[1]).unwrap().margin = f[2].parse().unwrap(),
            // Indices go through `f64` even though they are integers: `vec()` formats every
            // field with `format(digits = 17, scientific = TRUE)`, so an index arrives as `0e+00`
            // and `parse::<usize>` rejects it.
            // One record per row, so the shape is in the file rather than assumed. `f[2]` is the
            // 1-based row.
            "coord_row" => {
                let c = cases.get_mut(f[1]).unwrap();
                let r: usize = f[2].parse().unwrap();
                let d = c.d;
                let v = vec_f64_at(&f, 3);
                assert_eq!(
                    v.len(),
                    d,
                    "{}: coord_row {} has {} values, not d={d}",
                    f[1],
                    r,
                    v.len()
                );
                if c.coords.len() < r * d {
                    c.coords.resize(r * d, 0.0);
                }
                c.coords[(r - 1) * d..r * d].copy_from_slice(&v);
            }
            "ds_row" => {
                let c = cases.get_mut(f[1]).unwrap();
                let r: usize = f[2].parse().unwrap();
                let k = c.group_levels.len();
                c.want_d_spatial.resize(k * k, f64::NAN);
                let v = vec_f64_at(&f, 3);
                assert_eq!(
                    v.len(),
                    k,
                    "{}: ds_row {} has {} values, not k={k}",
                    f[1],
                    r,
                    v.len()
                );
                for (j, x) in v.iter().enumerate() {
                    c.want_d_spatial[(r - 1) * k + j] = *x;
                }
            }
            "ac_row" => {
                let c = cases.get_mut(f[1]).unwrap();
                let r: usize = f[2].parse().unwrap();
                let k = c.group_levels.len();
                c.want_adj_contact.resize(k * k, 0.0);
                let v = vec_f64_at(&f, 3);
                assert_eq!(
                    v.len(),
                    k,
                    "{}: ac_row {} has {} values, not k={k}",
                    f[1],
                    r,
                    v.len()
                );
                for (j, x) in v.iter().enumerate() {
                    c.want_adj_contact[(r - 1) * k + j] = *x;
                }
            }
            "group" => cases.get_mut(f[1]).unwrap().group_index = vec_usize(&f),
            "samples" => cases.get_mut(f[1]).unwrap().sample_index = vec_usize(&f),
            "d_dimnames" => {
                let v: Vec<String> = f[2].split(',').map(str::to_string).collect();
                cases.get_mut(f[1]).unwrap().want_dimnames = v;
            }
            "error" => cases.get_mut(f[1]).unwrap().error = Some(f[2].to_string()),
            other => panic!("unknown corpus record {other:?}"),
        }
    }
    (order, cases)
}

fn bits(v: f64) -> String {
    if v.is_nan() {
        "nan".to_string()
    } else {
        format!("{:016x}", v.to_bits())
    }
}

/// Report every mismatch rather than the first, so one failing fixture shows the whole shape of
/// the divergence instead of needing one run per wrong element.
fn check_matrix(label: &str, got: &[f64], want: &[f64], k: usize) {
    assert_eq!(
        got.len(),
        want.len(),
        "{label}: length {} vs {}",
        got.len(),
        want.len()
    );
    let mut bad = Vec::new();
    for i in 0..want.len() {
        if bits(got[i]) != bits(want[i]) {
            bad.push(format!(
                "[{i}] got {} want {} (row {}, col {})",
                got[i],
                want[i],
                i / k,
                i % k
            ));
        }
    }
    assert!(bad.is_empty(), "{label}:\n  {}", bad.join("\n  "));
}

fn run(c: &Case) -> Result<r_core::spatial::RegionOutput, RegionError> {
    let inp = RegionInput {
        coords: &c.coords,
        n: c.n,
        d: c.d,
        group_levels: &c.group_levels,
        group_index: &c.group_index,
        samples_levels: &c.samples_levels,
        sample_index: &c.sample_index,
        interaction_range: c.interaction_range,
        ratio: &c.ratio,
        tol: &c.tol,
        k_min: c.k_min,
        contact_dependent: c.contact_dependent,
        contact_range: c.contact_range,
        contact_knn_k: c.contact_knn_k,
        do_symmetric: c.do_symmetric,
    };
    region_distance(&inp)
}

/// The guard error, verbatim, so the shim's `stop()` is the only place a message is written.
#[test]
fn the_needs_contact_error_is_upstreams_message() {
    let (order, cases) = load();
    let mut seen = 0;
    for name in &order {
        let c = &cases[name];
        let Some(want) = &c.error else { continue };
        seen += 1;
        let err = run(c).expect_err("{name} should have failed");
        assert_eq!(
            err.to_string(),
            *want,
            "{name}: the error text is compared verbatim"
        );
    }
    assert_eq!(seen, 1, "the corpus should carry exactly one error case");
    // And the variant carries no text of its own that could drift.
    assert_eq!(
        run(&cases["err_needs_contact"]).unwrap_err(),
        RegionError::NeedsContactRangeOrKnn
    );
}

/// `d.spatial` and `adj.contact`, bit for bit, for every case that returns a value.
#[test]
fn region_distance_matches_upstreams_arithmetic() {
    let (order, cases) = load();
    let mut checked = 0;
    for name in &order {
        let c = &cases[name];
        if c.error.is_some() {
            continue;
        }
        let got = run(c).unwrap_or_else(|e| panic!("{name}: unexpected error {e}"));
        let k = c.group_levels.len();
        check_matrix(
            &format!("{name}: d.spatial"),
            &got.d_spatial,
            &c.want_d_spatial,
            k,
        );
        check_matrix(
            &format!("{name}: adj.contact"),
            &got.adj_contact,
            &c.want_adj_contact,
            k,
        );
        assert_eq!(
            got.adj_contact.len(),
            k * k,
            "{name}: adj.contact must be k x k"
        );
        assert_eq!(
            got.adj_contact_knn.len(),
            k * k,
            "{name}: adj.contact.knn must be k x k"
        );
        assert_eq!(
            got.group_levels, c.group_levels,
            "{name}: the level order is the factor's"
        );
        // Upstream's `dimnames` are the factor levels on both axes, and `identical()` sees the
        // row and column names separately, so check them as the corpus split them.
        assert_eq!(
            c.want_dimnames.len(),
            2 * k,
            "{name}: the corpus must carry both axes"
        );
        assert_eq!(
            &c.want_dimnames[..k],
            &c.want_dimnames[k..],
            "{name}: upstream uses the same levels for rows and columns"
        );
        assert_eq!(
            &got.group_levels[..],
            &c.want_dimnames[..k],
            "{name}: rownames must be the group levels in level order"
        );
        checked += 1;
    }
    assert_eq!(
        checked, 12,
        "the corpus should carry 12 value-returning cases"
    );
}

/// `NaN` must survive where upstream leaves it, not become `0`.
///
/// This is the fixture that keeps the distinction honest. `d.spatial` is `NaN` for a level
/// absent from the data, and the caller zeroes those with `P.spatial[is.na(d.spatial)] <- 0`, so a
/// port that returned `0` directly would look right everywhere except in the returned matrix --
/// and `identical()` is exactly the gate that catches it.
#[test]
fn an_absent_level_stays_nan_rather_than_becoming_zero() {
    let (_, cases) = load();
    let name = "declared_but_absent_level";
    let c = &cases[name];
    assert_eq!(c.group_levels.len(), 3, "{name}: must declare three levels");
    assert_eq!(
        c.group_levels[0], "C",
        "{name}: the absent level is declared first"
    );
    assert!(
        c.group_index.iter().all(|g| *g != 0),
        "{name}: level C must have no cells"
    );
    let k = c.group_levels.len();

    let got = run(c).expect("returns a value");
    // The empty row and column are the **trailing** ones, not C's. Upstream walks
    // `for (i in 1:numCluster)` and reads the level out of `level.use[i]`, so the loop counter
    // picks the slot and `level.use` picks the level. C is declared first, `level.use` is
    // `c("A","B")`, and A therefore lands in slot 1 -- which `rownames(d.spatial) <- levels(group)`
    // labels "C". Slot 3 is never written.
    //
    // So the returned `group_levels` **do not label the returned matrix**, and a caller that maps
    // `d.spatial[i, ]` back to `levels(group)[i]` is reading A's row as C. Reproducing the labels
    // faithfully means reproducing the mislabelling.
    for j in 0..k {
        assert!(
            got.d_spatial[2 * k + j].is_nan(),
            "{name}: d.spatial[2,{j}] must be NaN -- the third slot is never written"
        );
        assert!(
            got.d_spatial[j * k + 2].is_nan(),
            "{name}: d.spatial[{j},2] must be NaN for the same reason"
        );
        assert_eq!(
            got.adj_contact[2 * k + j],
            0.0,
            "{name}: adj.contact[2,{j}] must stay 0"
        );
    }
    // And the populated slots hold A and B, not C and A.
    assert_eq!(
        got.d_spatial[0], 0.0,
        "{name}: slot 1 is the diagonal of A's row"
    );
    assert_eq!(
        bits(got.d_spatial[1]),
        bits(c.want_d_spatial[1]),
        "{name}: slot 1 holds the A/B distance"
    );
    // The caller zeroes the `NaN`s -- `P.spatial[is.na(d.spatial)] <- 0` -- so a port that returned
    // 0 here instead of `NaN` would satisfy every caller and be caught only here.
    assert_eq!(
        got.d_spatial.iter().filter(|x| x.is_nan()).count(),
        2 * k - 1,
        "{name}: the unwritten row and column, minus the shared corner"
    );
}

/// `d.spatial` is `NaN` exactly where the groups are not adjacent.
///
/// `adj.spatial[adj.spatial == 0] <- NaN` followed by `d.spatial * adj.spatial` is the whole
/// mechanism, and it is asymmetric in a way worth pinning: `adj * t(adj)` zeroes a pair when
/// *either* direction is zero, so the two directions cannot disagree in the output.
#[test]
fn nan_in_d_spatial_marks_exactly_the_non_adjacent_pairs() {
    let (order, cases) = load();
    let mut saw_a_split = false;
    for name in &order {
        let c = &cases[name];
        if c.error.is_some() {
            continue;
        }
        let got = run(c).unwrap();
        let k = c.group_levels.len();
        // Symmetry, from `(d + t(d)) / 2` on the distances and `adj * t(adj)` on the adjacencies.
        for i in 0..k {
            for j in 0..k {
                assert_eq!(
                    got.adj_contact[i * k + j],
                    got.adj_contact[j * k + i],
                    "{name}: adj.contact must be symmetric at ({i},{j})"
                );
                assert_eq!(
                    bits(got.d_spatial[i * k + j]),
                    bits(got.d_spatial[j * k + i]),
                    "{name}: d.spatial must be symmetric at ({i},{j})"
                );
            }
        }

        // The `NaN` mask comes from `adj.spatial`, which is **not** part of the return value. When
        // `contact.knn.k` is absent the returned `adj.contact` *is* that same matrix, so the two
        // must agree entry for entry. When it is present, upstream swaps in `adj.contact.knn` and
        // the equivalence is simply gone -- so the test asserts the split exists rather than
        // requiring agreement, which would be a stricter claim than upstream makes.
        let agrees = (0..k * k).all(|i| got.d_spatial[i].is_nan() == (got.adj_contact[i] == 0.0));
        match c.contact_knn_k {
            None => assert!(
                agrees,
                "{name}: with no contact.knn.k the returned adj.contact *is* the matrix that \
                     masks d.spatial, so every NaN must be a non-adjacent entry"
            ),
            Some(_) => saw_a_split |= !agrees,
        }
    }
    assert!(
        saw_a_split,
        "some fixture must have contact.knn.k and a d.spatial NaN mask that disagrees with the \
         returned adj.contact, or the branch that swaps the two matrices is never exercised"
    );
}

/// Every recorded margin must still justify the generator's neighbour substitution.
///
/// The generator enforces this too, but enforcing it only where the layouts are *defined* means a
/// regenerated corpus under a changed constant looks fine. Checking the recorded number here makes
/// the property a property of the corpus, which is what the substitution needs.
#[test]
fn the_recorded_margins_hold_up() {
    const MIN_MARGIN: f64 = 2.0;
    let (order, cases) = load();
    for name in &order {
        let m = cases[name].margin;
        assert!(
            m.is_finite() && m > 0.0,
            "{name}: margin {m} must be a usable ratio"
        );
        assert!(
            m <= 1.0 / MIN_MARGIN,
            "{name}: d1/d2 is {m:.4}, so the runner-up is only {:.2}x the nearest distance; the \
             substitution of an exhaustive neighbour query for `AnnoyParam` needs at least \
             {MIN_MARGIN}x",
            1.0 / m
        );
    }
}

/// `contact.knn.k` *replaces* `adj.contact`; it does not merge with it.
///
/// `if (length(contact.knn.k) > 0) adj.contact = adj.contact.knn` means a pair that is within
/// `contact.range` in some sample but not in the nearest `k` neighbours of any sample ends up `0`
/// in the returned value. Reproducing that as a merge is the intuitive reading and it is wrong.
#[test]
fn contact_knn_k_replaces_rather_than_merges() {
    let (_, cases) = load();

    // Only `two_groups_knn` and `both_contact_rules` give `contact.knn.k` *and* a `contact.range`
    // or nothing else, and only the second has both rules able to disagree. With no
    // `contact.range` at all, `adj.contact` is 0 for every entry, so a merge would show up as an
    // all-zero result -- worth pinning, but it cannot tell a merge from a max.
    let both = &cases["both_contact_rules"];
    let got = run(both).expect("returns a value");
    assert_eq!(
        got.adj_contact, got.adj_contact_knn,
        "the returned adj.contact must be adj.contact.knn verbatim, not merged with it"
    );
    assert!(
        got.adj_contact.contains(&1.0),
        "the fixture must have a non-zero entry, else replacement and skipping are the same"
    );

    // Dropping `contact.knn.k` leaves the range-based count, and it is genuinely different here.
    let range_only = run(&Case {
        contact_knn_k: None,
        ..both.clone()
    })
    .expect("returns a value");
    assert_ne!(
        range_only.adj_contact, got.adj_contact,
        "with contact.knn.k removed the range-based adj.contact must differ, or the \
                fixture does not separate the two rules"
    );
    assert_ne!(
        range_only.adj_contact_knn, got.adj_contact_knn,
        "and adj.contact.knn must change too, since k.min.contact is k.min instead of -1"
    );

    // With no `contact.knn.k`, `k.min.contact` is -1 and `length(...) >= -1` holds, so
    // `adj.contact.knn` is all ones and is what gets returned.
    let with_range = run(&cases["two_groups_contact_range"]).expect("returns a value");
    assert!(
        with_range.adj_contact.iter().all(|x| *x == 1.0),
        "without contact.knn.k every adj.contact entry must be 1"
    );
    assert!(
        with_range.adj_contact_knn.iter().all(|x| *x == 1.0),
        "k.min.contact = -1 must make adj.contact.knn all ones"
    );
    assert_eq!(
        with_range.adj_contact_knn, with_range.adj_contact,
        "the all-ones adj.contact.knn must be what gets returned when it is supplied"
    );
}

/// `contact.dependent = FALSE` makes every entry 1, because upstream overwrites `contact.range`
/// with `10000`. Reproducing it as "skip the contact test" gives the same answer here *by accident*
/// -- the difference appears as soon as a layout has cells further apart than `10000`, so the
/// substitution is pinned rather than assumed.
#[test]
fn contact_independent_widens_the_range_rather_than_skipping_the_test() {
    let (_, cases) = load();
    let c = &cases["not_contact_dependent"];
    let off = run(c).expect("returns a value");

    // `contact.range <- 10000` when `contact.dependent` is `FALSE`, so **every** query passes the
    // range test and the entry becomes `length(unique(qout$index[all rows])) >= k.min` -- the
    // number of *distinct* target cells reached, which is not `nrow(idx.i)`. With `k.min = 2` and
    // three cells sharing one nearest neighbour that count is 1 and the entry is 0. Reading the
    // upstream comment "this produces adj.contact with all elements being 1" as a guarantee is
    // what makes this look like a port bug: the range is widened, the count is unchanged.
    for g in 0..c.group_levels.len() {
        assert_eq!(
            off.adj_contact[g * c.group_levels.len() + g],
            1.0,
            "the diagonal must be 1: the contact test ran rather than being skipped"
        );
    }

    // Turning `contact.dependent` back on restores `contact.range = 1`, a strictly narrower
    // threshold. Admitting more queries can only turn a 0 into a 1, so entrywise `>=` is the
    // property; equality everywhere would mean the flag was ignored.
    let on = run(&Case {
        contact_dependent: true,
        ..c.clone()
    })
    .expect("returns a value");
    for i in 0..off.adj_contact.len() {
        assert!(
            off.adj_contact[i] >= on.adj_contact[i],
            "entry {i}: widening contact.range must not turn a 1 into a 0 ({} < {})",
            off.adj_contact[i],
            on.adj_contact[i]
        );
    }
}

/// `tol` and `ratio` are per **sample**, and the corpus pins that with two-sample fixtures.
#[test]
fn ratio_and_tol_are_read_per_sample() {
    let (_, cases) = load();
    let c = &cases["two_samples"];
    assert_eq!(
        c.samples_levels.len(),
        2,
        "the fixture must have two samples"
    );
    assert_eq!(c.ratio.len(), 2, "ratio must carry one entry per sample");
    assert_eq!(c.tol.len(), 2, "tol must carry one entry per sample");
    assert_ne!(
        c.ratio[0], c.ratio[1],
        "the two samples must differ, or the fixture is vacuous"
    );
    let got = run(c).expect("returns a value");
    check_matrix(
        "two_samples: d.spatial",
        &got.d_spatial,
        &c.want_d_spatial,
        2,
    );
    check_matrix(
        "two_samples: adj.contact",
        &got.adj_contact,
        &c.want_adj_contact,
        2,
    );
}

/// A length-1 `ratio` is **recycled**, which is what upstream's `ratio[k]` does.
///
/// This is the case that was wrong first: the core indexed `ratio[s]` directly and panicked on the
/// two-sample fixture with a scalar `ratio`, which is the single most natural way to call this
/// function. R repeats a length-1 vector, so the core repeats it too.
#[test]
fn a_scalar_ratio_is_recycled_over_samples() {
    let (_, cases) = load();
    let c = cases["group_absent_in_one_sample"].clone();
    assert_eq!(
        c.samples_levels.len(),
        2,
        "the fixture must have two samples"
    );
    assert_eq!(c.ratio.len(), 1, "the corpus fixture uses a scalar ratio");
    let got = run(&c).expect("a scalar ratio must be recycled, not refused");
    check_matrix(
        "group_absent_in_one_sample: d.spatial",
        &got.d_spatial,
        &c.want_d_spatial,
        c.group_levels.len(),
    );
}

/// Any *other* short length is refused rather than read as `NA`.
///
/// R would return `NA` for the missing entries and silently produce `NaN` distances. A `NaN` that
/// means "you passed the wrong length" is indistinguishable from a `NaN` that means "these groups
/// are not adjacent", and the caller zeroes the latter without looking.
#[test]
fn a_ratio_that_is_neither_one_nor_n_is_refused() {
    let (_, cases) = load();
    let mut c = cases["two_samples"].clone();
    // Three samples, two entries: neither a scalar nor one per sample.
    c.samples_levels = vec!["s1".into(), "s2".into(), "s3".into()];
    let err = run(&c).expect_err("a two-entry ratio for three samples must be refused");
    assert!(
        matches!(err, RegionError::RatioOrTolTooShort { need: 3 }),
        "unexpected error {err:?}"
    );
    assert!(
        err.to_string().contains('3'),
        "the message should name the count it needed, got {err}"
    );
}
