//! Parity for `rankNet(mode = "comparison")` against the `cmp_*` records of
//! `tests/fixtures/ranknet_golden.txt`.
//!
//! Split from `ranknet_parity.rs` because the comparison branch is a different shape of thing: a
//! *list* of networks rather than one, a reassignment **pooled across** them, a union of pathway
//! vocabularies, and a multi-key `order()`. Sharing a file would bury both.
//!
//! The corpus is generated by `tests/parity/gen_ranknet_golden.R` from upstream's
//! `mode = "comparison"` body lifted verbatim, so the oracle is upstream's arithmetic. The
//! data-frame assembly -- `df[[i]][pair.name[[i]], 2] <- ...`, the `factor()` of `name`, the
//! `rev(levels(group))`, and `rbind`'s row-name uniquification -- is **not** here: it is
//! name-based bookkeeping with no arithmetic, and R's own `rbind` already implements the
//! uniquification exactly. The shim assembles; this pins the numbers and the order.
//!
//! Doubles are compared by bit pattern.

use r_core::ranknet::{comparison_flow, ComparisonIn, Measure};
use std::collections::HashMap;

#[derive(Debug, Default, Clone)]
struct CmpCase {
    measure: String,
    thresh: f64,
    ncomp: usize,
    /// Pathway names per comparison, in the comparison's own order.
    pair_names: Vec<Vec<String>>,
    levels: Vec<String>,
    prob: Vec<Vec<f64>>,
    pval: Vec<Vec<f64>>,
    sources_use: Option<Vec<usize>>,
    targets_use: Option<Vec<usize>>,
    // Expected, present only when the case returns a value.
    names_all: Vec<String>,
    values_assign: Vec<f64>,
    position: Vec<usize>,
    order: Vec<usize>,
    original: Vec<Vec<f64>>,
    scaled: Vec<Vec<f64>>,
    /// `None` means the record was absent, which upstream's `idx` is for `measure = "count"`.
    flagged: Vec<Option<Vec<usize>>>,
    contrib: Vec<Vec<f64>>,
    scaled_all: Vec<Vec<f64>>,
    /// `cmp_names_ordered`: `pair_names_all` permuted by upstream's `order()`. Recorded because it
    /// is the *shim's* output, not the kernel's -- the sort keys are R's `format(..., digits = 1)`
    /// values -- and this suite deliberately does not assert it. `check_identical.R` does, against
    /// upstream's real `rankNet`.
    #[allow(dead_code)]
    names_ordered: Vec<Vec<String>>,
    /// `cmp_ratio`: the unformatted `df[[ncomp-j]]$contribution / df[[1]]$contribution`.
    ratio: Vec<Vec<f64>>,
    /// `cmp_relative`: the same after R's `format(..., digits = 1)`. Recorded for reference and
    /// asserted end-to-end by the shim gate, not by this suite.
    relative: Vec<Vec<f64>>,
    object_names: Vec<String>,
    error: Option<String>,
}

fn num(s: &str) -> f64 {
    match s {
        "<NaN>" | "NaN" => f64::NAN,
        "<NA>" | "NA" => f64::NAN,
        "Inf" => f64::INFINITY,
        "-Inf" => f64::NEG_INFINITY,
        other => other.parse().expect("a corpus number must parse"),
    }
}

fn csv_f64(s: &str) -> Vec<f64> {
    if s == "-" {
        Vec::new()
    } else {
        s.split(',').map(num).collect()
    }
}

fn csv_usize(s: &str) -> Vec<usize> {
    if s == "-" {
        Vec::new()
    } else {
        s.split(',').map(|x| x.parse().unwrap()).collect()
    }
}

fn csv_names(s: &str) -> Vec<String> {
    if s == "-" {
        Vec::new()
    } else {
        s.split(',').map(str::to_string).collect()
    }
}

/// `names#i` -> `(names, i - 1)`, the key for every per-comparison record.
///
/// The corpus tag is **1-based** -- it is written by an R loop over `seq_len(ncomp)` -- while
/// every index in the Rust API is 0-based. Leaving the conversion out gives
/// `cmp_prob two_disjoint#2 is comparison 2 of 2`, which reads like a corpus bug and is a reader
/// bug. Converting here, once, is the only place the two conventions meet.
fn split_tag(tag: &str) -> (String, usize) {
    let (a, b) = tag
        .rsplit_once('#')
        .expect("a cmp record tag must carry a comparison index");
    let one_based: usize = b.parse().expect("the comparison index must parse");
    assert!(one_based >= 1, "corpus tags are 1-based, got {tag:?}");
    (a.to_string(), one_based - 1)
}

fn load() -> (Vec<String>, HashMap<String, CmpCase>) {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/ranknet_golden.txt");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut order: Vec<String> = Vec::new();
    let mut map: HashMap<String, CmpCase> = HashMap::new();
    let mut cur;
    for line in text.lines() {
        let f: Vec<&str> = line.split('\t').collect();
        let tag = f.get(1).copied().unwrap_or("");
        // Every `cmp_*` record the arms below read must carry at least a tag and a payload.
        // Without this the failure is `index out of bounds` on the *line*, which says nothing
        // about which record or which case.
        if f[0].starts_with("cmp_") && f.len() < 3 && f[0] != "cmp_case" {
            panic!("corpus record needs a payload: {line:?}");
        }
        match f[0] {
            "cmp_case" => {
                cur = tag.to_string();
                order.push(cur.clone());
                map.insert(cur.clone(), CmpCase::default());
            }
            "cmp_meta" => {
                let c = map.get_mut(f[1]).unwrap();
                c.measure = f[2].to_string();
                c.thresh = f[3].parse().unwrap();
                c.ncomp = f[4].parse().unwrap();
                c.pair_names = f[5]
                    .split(';')
                    .map(|g| g.split(',').map(str::to_string).collect())
                    .collect();
                c.prob = vec![Vec::new(); c.ncomp];
                c.pval = vec![Vec::new(); c.ncomp];
                c.original = vec![Vec::new(); c.ncomp];
                c.scaled = vec![Vec::new(); c.ncomp];
                c.flagged = vec![None; c.ncomp];
                c.contrib = vec![Vec::new(); c.ncomp];
                c.scaled_all = vec![Vec::new(); c.ncomp];
                c.names_ordered = vec![Vec::new(); c.ncomp];
                c.ratio = Vec::new();
                c.relative = Vec::new();
            }
            "cmp_levels" => {
                map.get_mut(f[1]).unwrap().levels = f[2].split(',').map(str::to_string).collect()
            }
            "cmp_sources" => {
                let c = map.get_mut(f[1]).unwrap();
                c.sources_use = if f[2] == "-" {
                    None
                } else {
                    Some(resolve(f[2], &c.levels))
                };
            }
            "cmp_targets" => {
                let c = map.get_mut(f[1]).unwrap();
                c.targets_use = if f[2] == "-" {
                    None
                } else {
                    Some(resolve(f[2], &c.levels))
                };
            }
            "cmp_prob" | "cmp_pval" | "cmp_original" | "cmp_scaled" | "cmp_contrib"
            | "cmp_scaled_all" => {
                let (nm, i) = split_tag(tag);
                let v: Vec<f64> = f[2..].iter().map(|x| num(x)).collect();
                let c = map.get_mut(&nm).unwrap();
                match f[0] {
                    "cmp_prob" => c.prob[i] = v,
                    "cmp_pval" => c.pval[i] = v,
                    "cmp_original" => c.original[i] = v,
                    "cmp_scaled" => c.scaled[i] = v,
                    "cmp_contrib" => c.contrib[i] = v,
                    _ => c.scaled_all[i] = v,
                }
            }
            "cmp_names_ordered" => {
                let (nm, i) = split_tag(tag);
                map.get_mut(&nm).unwrap().names_ordered[i] = csv_names(f[2]);
            }
            "cmp_flagged" => {
                let (nm, i) = split_tag(tag);
                // `which()` is 1-based; every index in the Rust API is 0-based.
                map.get_mut(&nm).unwrap().flagged[i] = if f[2] == "-" {
                    None
                } else {
                    Some(csv_usize(f[2]).iter().map(|x| x - 1).collect())
                };
            }
            "cmp_ratio" | "cmp_relative" => {
                // `contribution.relative.j` is 1-based in the corpus; pushed in order so the
                // index is not needed, but it is still converted rather than discarded silently.
                let (nm, _j) = split_tag(tag);
                // TAB-separated, like every other `cmp_*` vector record. `csv_f64` reads it as
                // one number, and the length mismatch then surfaces three assertions later as
                // "5 values vs 1", naming the wrong thing entirely.
                let v: Vec<f64> = f[2..].iter().map(|x| num(x)).collect();
                let c = map.get_mut(&nm).unwrap();
                if f[0] == "cmp_ratio" {
                    c.ratio.push(v)
                } else {
                    c.relative.push(v)
                }
            }
            "cmp_names_all" => map.get_mut(f[1]).unwrap().names_all = csv_names(f[2]),
            "cmp_values_assign" => map.get_mut(f[1]).unwrap().values_assign = csv_f64(f[2]),
            "cmp_position" => map.get_mut(f[1]).unwrap().position = csv_usize(f[2]),
            "cmp_order" => map.get_mut(f[1]).unwrap().order = csv_usize(f[2]),
            "cmp_object_names" => map.get_mut(f[1]).unwrap().object_names = csv_names(f[2]),
            "cmp_error" => map.get_mut(f[1]).unwrap().error = Some(f[2].to_string()),
            // Records belonging to the single-network cases live in the same file.
            _ => {}
        }
    }
    (order, map)
}

/// `sources.use` / `targets.use` are group *names* here, resolved against the level vector --
/// and upstream validates `targets.use` against the **first** axis too, so a name that exists
/// only as a target is accepted and then matches nothing. Resolving against one shared level
/// list reproduces that.
fn resolve(names: &str, levels: &[String]) -> Vec<usize> {
    names
        .split(',')
        .map(|n| {
            levels
                .iter()
                .position(|l| l == n)
                .unwrap_or_else(|| panic!("{n} must be a group level"))
        })
        .collect()
}

fn run(c: &CmpCase) -> Result<r_core::ranknet::ComparisonOut, r_core::ranknet::RankNetError> {
    let m = Measure::from_name(&c.measure).expect("the corpus only uses weight and count");
    comparison_flow(&ComparisonIn {
        prob: &c.prob,
        pval: &c.pval,
        k: 4,
        pair_names: &c.pair_names,
        measure: m,
        thresh: c.thresh,
        sources_use: c.sources_use.as_deref(),
        targets_use: c.targets_use.as_deref(),
    })
}

fn bits(v: f64) -> String {
    if v.is_nan() {
        "nan".to_string()
    } else {
        format!("{:016x}", v.to_bits())
    }
}

fn check(label: &str, got: &[f64], want: &[f64]) {
    assert_eq!(
        got.len(),
        want.len(),
        "{label}: {} values vs {}",
        got.len(),
        want.len()
    );
    let bad: Vec<String> = (0..want.len())
        .filter(|&i| bits(got[i]) != bits(want[i]))
        .map(|i| format!("[{i}] got {} want {}", got[i], want[i]))
        .collect();
    assert!(bad.is_empty(), "{label}:\n  {}", bad.join("\n  "));
}

/// Every value-returning case, bit for bit.
#[test]
fn the_comparison_flow_matches_upstream() {
    let (order, cases) = load();
    let mut checked = 0;
    for name in &order {
        let c = &cases[name];
        if c.error.is_some() {
            continue;
        }
        let got = run(c).unwrap_or_else(|e| panic!("{name}: unexpected error {e:?}"));
        assert_eq!(
            got.pair_names_all, c.names_all,
            "{name}: pair.name.all is a union in first-appearance order"
        );
        for i in 0..c.ncomp {
            let tag = format!("{name}#{i}");
            check(&format!("{tag} original"), &got.original[i], &c.original[i]);
            check(&format!("{tag} scaled"), &got.scaled[i], &c.scaled[i]);
            // `contribution` and `contribution.scaled` are the frame's columns after the
            // row-name-indexed assignment, i.e. over `pair.name_all` with absent pathways at 0.
            check(
                &format!("{tag} contribution"),
                &contrib_of(&got, i),
                &c.contrib[i],
            );
            check(
                &format!("{tag} contribution.scaled"),
                &scaled_of(&got, i),
                &c.scaled_all[i],
            );
            assert_eq!(
                got.flagged[i],
                c.flagged[i].as_deref().unwrap_or(&[]),
                "{tag}: `which(is.infinite | < 0)`, 0-based"
            );
        }
        // `cmp_ratio` is the unformatted ratio the kernel returns; `cmp_relative` is what R's
        // `format(..., digits = 1)` makes of it, and the shim applies that in R because
        // `format` is vector-dependent. Only the former is a kernel quantity.
        for (j, want) in c.ratio.iter().enumerate() {
            check(&format!("{name}: ratio.{}", j + 1), &got.ratio[j], want);
        }
        assert_eq!(
            got.ratio.len(),
            c.ncomp - 1,
            "{name}: one ratio per comparison beyond the first"
        );
        checked += 1;
    }
    assert_eq!(
        checked, 6,
        "the corpus should carry 6 value-returning comparison cases"
    );
}

/// `contribution` for comparison `i`: the per-pathway totals placed into `pair.name_all`'s order,
/// with pathways the comparison does not have left at 0.
fn contrib_of(got: &r_core::ranknet::ComparisonOut, i: usize) -> Vec<f64> {
    let mut v = vec![0.0f64; got.pair_names_all.len()];
    for (t, nm) in got.pair_names_here[i].iter().enumerate() {
        let a = got
            .pair_names_all
            .iter()
            .position(|x| x == nm)
            .expect("in pair_names_all");
        v[a] = got.original[i][t];
    }
    v
}

fn scaled_of(got: &r_core::ranknet::ComparisonOut, i: usize) -> Vec<f64> {
    let mut v = vec![0.0f64; got.pair_names_all.len()];
    for (t, nm) in got.pair_names_here[i].iter().enumerate() {
        let a = got
            .pair_names_all
            .iter()
            .position(|x| x == nm)
            .expect("in pair_names_all");
        v[a] = got.scaled[i][t];
    }
    v
}

/// The degenerate reassignment is **pooled**, not per comparison.
///
/// `pooled_degenerate` has a flagged pathway in *each* of two comparisons. Upstream builds one
/// `values.assign` from `max(unlist(pSum))` across both, one `pSum.original.all`, and one
/// `position` from sorting that; each comparison's slice is addressed by an offset into the
/// pooled sequence. Reassigning per comparison -- which is exactly what `mode = "single"`
/// degenerates to, and the obvious generalisation -- gives different assigned values and
/// therefore a different row order.
#[test]
fn the_reassignment_is_pooled_across_comparisons() {
    let (_, cases) = load();
    let c = &cases["pooled_degenerate"];
    let got = run(c).unwrap();
    assert_eq!(
        c.flagged[0].as_ref().unwrap().len() + c.flagged[1].as_ref().unwrap().len(),
        4,
        "the pooled values.assign must span both comparisons"
    );
    // A per-comparison reassignment would give each comparison a `values.assign` of length 2 and
    // the same two values for both. Pooled, the four assigned values strictly increase.
    let mut assigned: Vec<f64> = Vec::new();
    for i in 0..c.ncomp {
        for t in c.flagged[i].as_ref().unwrap() {
            assigned.push(got.scaled[i][*t]);
        }
    }
    assert_eq!(assigned.len(), 4);
    // The four assigned values are exactly the pooled `values.assign`, in *ranked* order rather
    // than comparison order -- `position` records the ranking, and two of the flagged totals are
    // equal, so a stable sort keeps their pooled order. Reading "the assigned values increase
    // across the comparisons" is simply false here: comparison 2's first flagged entry ranks
    // *above* comparison 1's second.
    let mut ranked = assigned.clone();
    ranked.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let mut want = c.values_assign.clone();
    want.sort_by(|a, b| a.partial_cmp(b).unwrap());
    assert_eq!(
        ranked, want,
        "the assigned values must be the pooled values.assign"
    );

    // And a per-comparison reassignment would give each comparison a `seq(lo, hi, length.out = 2)`
    // of its own -- four *different* numbers, so this case cannot be satisfied that way.
    let lo = c.scaled[0]
        .iter()
        .copied()
        .filter(|v| *v > 0.0)
        .fold(f64::MIN, f64::max)
        * 1.1;
    let hi = c.scaled[0]
        .iter()
        .copied()
        .filter(|v| *v > 0.0)
        .fold(f64::MIN, f64::max)
        * 1.5;
    let per_comparison = [lo, hi];
    assert!(
        !assigned.iter().all(|a| per_comparison.contains(a)),
        "a per-comparison reassignment would have produced {per_comparison:?}, so this fixture \
         does not distinguish the two"
    );
    // And every assigned value sits above the largest *unflagged* scaled value, which is the
    // point of the reassignment: a degenerate pathway is placed above the ordinary range.
    // The ordinary maximum is over the **unflagged** entries only. Taking it over the whole
    // scaled vector would include the assigned values themselves, which are by construction the
    // largest, and the assertion would degenerate to `x > x`.
    let mut ordinary = f64::MIN;
    for i in 0..c.ncomp {
        for (t, &v) in got.scaled[i].iter().enumerate() {
            if !c.flagged[i].as_ref().unwrap().contains(&t) && v > ordinary {
                ordinary = v;
            }
        }
    }
    for a in &assigned {
        assert!(
            *a > ordinary,
            "assigned {a} should sit above the ordinary maximum {ordinary}"
        );
    }
}

/// `Inf` in a relative contribution is real and has to survive.
///
/// A pathway absent from the **first** comparison has `contribution == 0` there, so
/// `df[[last]]$contribution / df[[1]]$contribution` is a positive number over zero, i.e. `Inf`.
/// `format(Inf, digits = 1)` is `"Inf"` and `as.numeric("Inf")` is `Inf`, so the `is.na` reset
/// upstream applies immediately afterwards does **not** touch it. Treating "absent" as zero --
/// or mapping `Inf` to `NA` alongside `NaN` -- puts the row in a different place under
/// `-contribution.relative`.
#[test]
fn an_absent_pathway_in_the_first_comparison_sorts_first() {
    let (_, cases) = load();
    let c = &cases["two_disjoint"];
    let got = run(c).unwrap();
    let x = c
        .names_all
        .iter()
        .position(|n| n == "X")
        .expect("X is in the union");
    assert!(
        got.ratio[0][x].is_infinite(),
        "X is absent from comparison 1, so its ratio is Inf, got {}",
        got.ratio[0][x]
    );
    // `X` is *not* flagged as `NaN`: `is.na(Inf)` is `FALSE`, so the reset must leave it alone.
    for r in &got.ratio {
        for v in r {
            assert!(
                !v.is_nan(),
                "the is.na reset upstream applies turns NaN into 0, never Inf into 0"
            );
        }
    }
}

/// Every comparison's `pSum` outside the unit interval is flagged, so the flag is a *range* and
/// not a single-point special case. This is the assertion the single-network suite cannot make
/// on its own, because it only ever has one network to pool over.
#[test]
fn every_total_at_or_above_one_is_flagged() {
    let (_, cases) = load();
    let c = &cases["pooled_degenerate"];
    for (i, orig) in c.original.iter().enumerate() {
        for (t, &v) in orig.iter().enumerate() {
            let flagged = c.flagged[i].as_ref().unwrap().contains(&t);
            assert_eq!(
                flagged,
                v >= 1.0,
                "comparison {i} pathway {t}: total {v} -- -1/log(x) is negative for every x > 1, \
                 so the flag is a range and log(1) == 0 is only its boundary"
            );
        }
    }
}

/// The stop paths, verbatim.
#[test]
fn the_comparison_errors_are_upstreams_messages() {
    let (order, cases) = load();
    let mut seen = 0;
    for name in &order {
        let c = &cases[name];
        let Some(want) = &c.error else { continue };
        seen += 1;
        let err = run(c).expect_err(&format!("{name} should have failed"));
        assert_eq!(
            err.to_string(),
            *want,
            "{name}: the error text is compared verbatim"
        );
    }
    assert_eq!(
        seen, 3,
        "the corpus should carry three comparison error cases"
    );
    assert_eq!(
        run(&cases["all_degenerate"]).unwrap_err().to_string(),
        "'from' must be a finite number"
    );
    assert_eq!(
        run(&cases["thresh_empties_second"])
            .unwrap_err()
            .to_string(),
        "No inferred communications for the input!"
    );
}

/// The `sum(prob) == 0` stop is checked **inside** the per-comparison loop, so a comparison that
/// empties stops the call even when an earlier comparison was fine.
#[test]
fn a_later_comparison_can_stop_an_earlier_valid_one() {
    let (_, cases) = load();
    let c = &cases["thresh_empties_second"];
    assert!(
        c.pval[0].iter().all(|v| *v <= c.thresh),
        "the first comparison survives the cut"
    );
    assert!(
        c.pval[1].iter().all(|v| *v > c.thresh),
        "the second does not"
    );
    assert!(matches!(
        run(c),
        Err(r_core::ranknet::RankNetError::NoCommunications)
    ));
}

/// `count` never populates `idx`, so `flagged` is absent rather than empty -- "no flagged entries"
/// and "this list was never built" are different facts.
#[test]
fn the_count_measure_populates_no_flags() {
    let (_, cases) = load();
    let c = &cases["count_measure"];
    let got = run(c).unwrap();
    for i in 0..c.ncomp {
        assert!(
            c.flagged[i].is_none(),
            "comparison {i}: upstream leaves `idx` as list() for count"
        );
        assert!(got.flagged[i].is_empty());
        // No transform, so `pSum == pSum.original`.
        assert_eq!(got.scaled[i], got.original[i]);
    }
}
