#!/usr/bin/env python3
"""Generate the complete delegated CellChat API from the verified bundled source.

Rust-backed functions remain in modeling.R. All other public functions retain the
original argument order and defaults and evaluate the original bundled R body.
No original CellChat installation or checkout is required.
"""
import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUNDLE = ROOT / "inst/upstream/CellChat-75253cd0"
PORTED = {
    "computeCommunProb", "computeCommunProbPathway", "identifyOverExpressedGenes",
    "filterCommunication", "subsetCommunication", "rankNet", "rankNetPairwise",
    "computeCellDistance", "computeRegionDistance", "netAnalysis_computeCentrality",
}


def main():
    # Parse functions without executing class definitions, imports, or top-level code.
    script = r'''
    result <- list()
    for (path in list.files("inst/upstream/CellChat-75253cd0/R", "\\.R$", full.names=TRUE)) {
      for (expr in parse(path)) {
        if (is.call(expr) && as.character(expr[[1]]) %in% c("<-", "=") &&
            is.symbol(expr[[2]]) && is.call(expr[[3]]) &&
            identical(expr[[3]][[1]], as.name("function"))) {
          fun <- eval(expr[[3]], baseenv())
          result[[as.character(expr[[2]])]] <- list(file=basename(path),
            signature=paste(deparse(args(fun), width.cutoff=500), collapse=" "))
        }
      }
    }
    cat(jsonlite::toJSON(result, auto_unbox=TRUE))
    '''
    env = dict(os.environ)
    env["R_LIBS"] = str(ROOT / ".rlib") + (":" + env["R_LIBS"] if env.get("R_LIBS") else "")
    funcs = json.loads(subprocess.check_output(["Rscript", "-e", script], cwd=ROOT, env=env))
    exports = re.findall(r"^export\(([^)]+)\)$", (BUNDLE / "NAMESPACE").read_text(), re.M)
    delegated = sorted(set(exports) - PORTED)
    parts = ["# Generated by scripts/gen_delegate.py from the pinned bundled CellChat API.\n"
             "# Delegated functions preserve upstream formals and evaluate bundled R code.\n"]
    for name in delegated:
        info = funcs[name]
        sig = re.sub(r"\s*NULL$", "", info["signature"])
        parts.append(f'''#' The pinned upstream `{name}`, with its original arguments.
#' @export
{name} <- {sig} {{
  call <- match.call()
  call[[1L]] <- get("{name}", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}}
''')
    (ROOT / "R/delegate.R").write_text("\n".join(parts))
    ns = (ROOT / "NAMESPACE").read_text()
    for name in delegated:
        line = f"export({name})"
        if line not in ns.splitlines(): ns += line + "\n"
    (ROOT / "NAMESPACE").write_text(ns)
    print(f"generated {len(delegated)} delegates with matching upstream formals")


if __name__ == "__main__":
    main()
