# Generated by scripts/gen_delegate.py from the pinned bundled CellChat API.
# Delegated functions preserve upstream formals and evaluate bundled R code.

#' The pinned upstream `CellChat_theme_opts`, with its original arguments.
#' @export
CellChat_theme_opts <- function () {
  call <- match.call()
  call[[1L]] <- get("CellChat_theme_opts", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `StackedVlnPlot`, with its original arguments.
#' @export
StackedVlnPlot <- function (object, features, idents = NULL, split.by = NULL, color.use = NULL, colors.ggplot = FALSE, angle.x = 90, vjust.x = NULL, hjust.x = NULL, show.text.y = TRUE, line.size = NULL, pt.size = 0, plot.margin = margin(0, 0, 0, 0, "cm"), ...) {
  call <- match.call()
  call[[1L]] <- get("StackedVlnPlot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `addMeta`, with its original arguments.
#' @export
addMeta <- function (object, meta, meta.name = NULL) {
  call <- match.call()
  call[[1L]] <- get("addMeta", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `addReduction`, with its original arguments.
#' @export
addReduction <- function (object, dr = NULL, dr.name = NULL, seu.obj = NULL, dr.use = NULL, force.add = FALSE) {
  call <- match.call()
  call[[1L]] <- get("addReduction", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `barPlot`, with its original arguments.
#' @export
barPlot <- function (object, features, group.by = NULL, split.by = NULL, color.use = NULL, method = c("truncatedMean", "triMean", "median"), trim = 0.1, assay = "RNA", x.lab.rot = FALSE, ncol = 1, ...) {
  call <- match.call()
  call[[1L]] <- get("barPlot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `barplot_internal`, with its original arguments.
#' @export
barplot_internal <- function (df, x = "cellType", y = "value", fill = "condition", legend.title = NULL, width = 0.6, title.name = NULL, xlabel = NULL, ylabel = NULL, color.use = NULL, remove.xtick = FALSE, stat.add = FALSE, stat.method = "wilcox.test", percent.y = FALSE, label.x = 1.5, show.legend = TRUE, x.lab.rot = FALSE, size.text = 10) {
  call <- match.call()
  call[[1L]] <- get("barplot_internal", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `buildSNN`, with its original arguments.
#' @export
buildSNN <- function (data.use, k = 10, k.scale = 10, prune.SNN = 1/15) {
  call <- match.call()
  call[[1L]] <- get("buildSNN", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `checkGeneSymbol`, with its original arguments.
#' @export
checkGeneSymbol <- function (geneSet, geneIfo) {
  call <- match.call()
  call[[1L]] <- get("checkGeneSymbol", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `colorRamp3`, with its original arguments.
#' @export
colorRamp3 <- function (breaks, colors, transparency = 0, space = "LAB") {
  call <- match.call()
  call[[1L]] <- get("colorRamp3", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `compareInteractions`, with its original arguments.
#' @export
compareInteractions <- function (object, measure = c("count", "weight"), color.use = NULL, group = NULL, group.levels = NULL, group.facet = NULL, group.facet.levels = NULL, n.row = 1, color.alpha = 1, legend.title = NULL, width = 0.6, title.name = NULL, digits = 3, xlabel = NULL, ylabel = NULL, remove.xtick = FALSE, show.legend = TRUE, x.lab.rot = FALSE, angle.x = 45, vjust.x = NULL, hjust.x = 1, size.text = 10) {
  call <- match.call()
  call[[1L]] <- get("compareInteractions", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeEigengap`, with its original arguments.
#' @export
computeEigengap <- function (CM, tau = NULL, tol = 0.01) {
  call <- match.call()
  call[[1L]] <- get("computeEigengap", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeEnrichmentScore`, with its original arguments.
#' @export
computeEnrichmentScore <- function (df, measure = c("ligand", "signaling", "LR-pair"), variable.both = TRUE, species = c("mouse", "human"), db = NULL, color.use = NULL, color.name = "Dark2", n.color = 8, scale = c(4, 0.8), min.freq = 0, max.words = 200, random.order = FALSE, rot.per = 0, return.data = FALSE, seed = 1, ...) {
  call <- match.call()
  call[[1L]] <- get("computeEnrichmentScore", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExprGroup_agonist`, with its original arguments.
#' @export
computeExprGroup_agonist <- function (data.use, pairLRsig, cofactor_input, group, index.agonist, Kh, FunMean, n) {
  call <- match.call()
  call[[1L]] <- get("computeExprGroup_agonist", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExprGroup_antagonist`, with its original arguments.
#' @export
computeExprGroup_antagonist <- function (data.use, pairLRsig, cofactor_input, group, index.antagonist, Kh, FunMean, n) {
  call <- match.call()
  call[[1L]] <- get("computeExprGroup_antagonist", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExpr_LR`, with its original arguments.
#' @export
computeExpr_LR <- function (geneLR, data.use, complex_input) {
  call <- match.call()
  call[[1L]] <- get("computeExpr_LR", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExpr_agonist`, with its original arguments.
#' @export
computeExpr_agonist <- function (data.use, pairLRsig, cofactor_input, index.agonist, Kh, n) {
  call <- match.call()
  call[[1L]] <- get("computeExpr_agonist", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExpr_antagonist`, with its original arguments.
#' @export
computeExpr_antagonist <- function (data.use, pairLRsig, cofactor_input, index.antagonist, Kh, n) {
  call <- match.call()
  call[[1L]] <- get("computeExpr_antagonist", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExpr_complex`, with its original arguments.
#' @export
computeExpr_complex <- function (complex_input, data.use, complex) {
  call <- match.call()
  call[[1L]] <- get("computeExpr_complex", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeExpr_coreceptor`, with its original arguments.
#' @export
computeExpr_coreceptor <- function (cofactor_input, data.use, pairLRsig, type = c("A", "I")) {
  call <- match.call()
  call[[1L]] <- get("computeExpr_coreceptor", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeLaplacian`, with its original arguments.
#' @export
computeLaplacian <- function (CM, tol = 0.01) {
  call <- match.call()
  call[[1L]] <- get("computeLaplacian", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeNetD_structure`, with its original arguments.
#' @export
computeNetD_structure <- function (g, h, w1 = 0.45, w2 = 0.45, w3 = 0.1) {
  call <- match.call()
  call[[1L]] <- get("computeNetD_structure", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeNetSimilarity`, with its original arguments.
#' @export
computeNetSimilarity <- function (object, slot.name = "netP", type = c("functional", "structural"), k = NULL, thresh = NULL) {
  call <- match.call()
  call[[1L]] <- get("computeNetSimilarity", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `computeNetSimilarityPairwise`, with its original arguments.
#' @export
computeNetSimilarityPairwise <- function (object, slot.name = "netP", type = c("functional", "structural"), comparison = NULL, k = NULL, thresh = NULL) {
  call <- match.call()
  call[[1L]] <- get("computeNetSimilarityPairwise", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `createCellChat`, with its original arguments.
#' @export
createCellChat <- function (object, meta = NULL, group.by = NULL, datatype = c("RNA", "spatial"), coordinates = NULL, spatial.factors = NULL, assay = NULL, do.sparse = T) {
  call <- match.call()
  call[[1L]] <- get("createCellChat", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `dotPlot`, with its original arguments.
#' @export
dotPlot <- function (object, features, rotation = TRUE, colormap = "OrRd", color.direction = 1, color.use = c("#F8766D", "#00BFC4"), scale = TRUE, col.min = -2.5, col.max = 2.5, dot.scale = 6, assay = "RNA", idents = NULL, group.by = NULL, split.by = NULL, legend.width = 0.5, angle.x = 45, hjust.x = 1, angle.y = 0, hjust.y = 0.5, show.legend = TRUE, ...) {
  call <- match.call()
  call[[1L]] <- get("dotPlot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `extractEnrichedLR`, with its original arguments.
#' @export
extractEnrichedLR <- function (object, signaling, geneLR.return = FALSE, enriched.only = TRUE, thresh = 0.05, geneInfo = NULL, complex_input = NULL) {
  call <- match.call()
  call[[1L]] <- get("extractEnrichedLR", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `extractGene`, with its original arguments.
#' @export
extractGene <- function (CellChatDB) {
  call <- match.call()
  call[[1L]] <- get("extractGene", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `extractGeneSubset`, with its original arguments.
#' @export
extractGeneSubset <- function (geneSet, complex_input, geneIfo) {
  call <- match.call()
  call[[1L]] <- get("extractGeneSubset", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `extractGeneSubsetFromPair`, with its original arguments.
#' @export
extractGeneSubsetFromPair <- function (pairLR, object = NULL, complex_input = NULL, geneInfo = NULL, combined = TRUE) {
  call <- match.call()
  call[[1L]] <- get("extractGeneSubsetFromPair", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `extractLRfromGenes`, with its original arguments.
#' @export
extractLRfromGenes <- function (geneSet, db) {
  call <- match.call()
  call[[1L]] <- get("extractLRfromGenes", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `findEnrichedSignaling`, with its original arguments.
#' @export
findEnrichedSignaling <- function (object, features, idents = NULL, pattern = c("both", "outgoing", "incoming"), thresh = 0.05) {
  call <- match.call()
  call[[1L]] <- get("findEnrichedSignaling", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `geometricMean`, with its original arguments.
#' @export
geometricMean <- function (x, na.rm = TRUE) {
  call <- match.call()
  call[[1L]] <- get("geometricMean", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `getMaxWeight`, with its original arguments.
#' @export
getMaxWeight <- function (object.list, slot.name = c("idents", "net"), attribute = c("idents", "count")) {
  call <- match.call()
  call[[1L]] <- get("getMaxWeight", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `ggPalette`, with its original arguments.
#' @export
ggPalette <- function (n) {
  call <- match.call()
  call[[1L]] <- get("ggPalette", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `identifyCommunicationPatterns`, with its original arguments.
#' @export
identifyCommunicationPatterns <- function (object, slot.name = "netP", pattern = c("outgoing", "incoming"), k = NULL, k.range = seq(2, 10), heatmap.show = TRUE, color.use = NULL, color.heatmap = "Spectral", title.legend = "Contributions", width = 4, height = 6, font.size = 8) {
  call <- match.call()
  call[[1L]] <- get("identifyCommunicationPatterns", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `identifyEnrichedInteractions`, with its original arguments.
#' @export
identifyEnrichedInteractions <- function (object, from, to, bidirection = FALSE, pair.only = TRUE, pairLR.use0 = NULL, thresh = 0.05) {
  call <- match.call()
  call[[1L]] <- get("identifyEnrichedInteractions", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `identifyOverExpressedInteractions`, with its original arguments.
#' @export
identifyOverExpressedInteractions <- function (object, features.name = "features", variable.both = TRUE, features = NULL, return.object = TRUE) {
  call <- match.call()
  call[[1L]] <- get("identifyOverExpressedInteractions", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `identifyOverExpressedLigandReceptor`, with its original arguments.
#' @export
identifyOverExpressedLigandReceptor <- function (object, features.name = "features", features = NULL, return.object = TRUE) {
  call <- match.call()
  call[[1L]] <- get("identifyOverExpressedLigandReceptor", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `liftCellChat`, with its original arguments.
#' @export
liftCellChat <- function (object, group.new = NULL) {
  call <- match.call()
  call[[1L]] <- get("liftCellChat", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `mergeCellChat`, with its original arguments.
#' @export
mergeCellChat <- function (object.list, add.names = NULL, merge.data = FALSE, cell.prefix = FALSE) {
  call <- match.call()
  call[[1L]] <- get("mergeCellChat", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `mergeInteractions`, with its original arguments.
#' @export
mergeInteractions <- function (object, group.merged) {
  call <- match.call()
  call[[1L]] <- get("mergeInteractions", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_contribution`, with its original arguments.
#' @export
netAnalysis_contribution <- function (object, signaling, signaling.name = NULL, sources.use = NULL, targets.use = NULL, width = 0.1, vertex.receiver = NULL, thresh = 0.05, return.data = FALSE, x.rotation = 0, title = "Contribution of each L-R pair", font.size = 10, font.size.title = 10) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_contribution", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_diff_signalingRole_scatter`, with its original arguments.
#' @export
netAnalysis_diff_signalingRole_scatter <- function (object, color.use = NULL, comparison = c(1, 2), signaling = NULL, signaling.exclude = NULL, idents.exclude = NULL, slot.name = "netP", group = NULL, dot.size = 2.5, point.shape = c(21, 22, 24, 23, 25, 8, 3), label.size = 3, dot.alpha = 0.6, x.measure = "outdeg", y.measure = "indeg", xlabel = "Outgoing interaction strength", ylabel = "Incoming interaction strength", title = NULL, font.size = 10, font.size.title = 10, do.label = T, show.legend = T, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_diff_signalingRole_scatter", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_dot`, with its original arguments.
#' @export
netAnalysis_dot <- function (object, slot.name = "netP", pattern = c("outgoing", "incoming"), cutoff = NULL, color.use = NULL, pathway.show = NULL, group.show = NULL, shape = 21, dot.size = c(1, 3), dot.alpha = 1, main.title = NULL, font.size = 10, font.size.title = 12) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_dot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_river`, with its original arguments.
#' @export
netAnalysis_river <- function (object, slot.name = "netP", pattern = c("outgoing", "incoming"), cutoff = 0.5, sources.use = NULL, targets.use = NULL, signaling = NULL, color.use = NULL, color.use.pattern = NULL, color.use.signaling = "grey50", do.order = FALSE, main.title = NULL, font.size = 2.5, font.size.title = 12) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_river", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_signalingChanges_scatter`, with its original arguments.
#' @export
netAnalysis_signalingChanges_scatter <- function (object, idents.use, color.use = c("grey10", "#F8766D", "#00BFC4"), comparison = c(1, 2), signaling = NULL, signaling.label = NULL, top.label = 1, signaling.exclude = NULL, xlims = NULL, ylims = NULL, slot.name = "netP", dot.size = 2.5, point.shape = c(21, 22, 24, 23), label.size = 3, dot.alpha = 0.6, x.measure = "outdeg", y.measure = "indeg", xlabel = "Differential outgoing interaction strength", ylabel = "Differential incoming interaction strength", title = NULL, font.size = 10, font.size.title = 10,      do.label = T, show.legend = T, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_signalingChanges_scatter", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_signalingRole_heatmap`, with its original arguments.
#' @export
netAnalysis_signalingRole_heatmap <- function (object, signaling = NULL, pattern = c("outgoing", "incoming", "all"), slot.name = "netP", color.use = NULL, color.heatmap = "BuGn", title = NULL, width = 10, height = 8, ylim.top = NULL, ylim.right = NULL, font.size = 8, font.size.title = 10, cluster.rows = FALSE, cluster.cols = FALSE) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_signalingRole_heatmap", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_signalingRole_network`, with its original arguments.
#' @export
netAnalysis_signalingRole_network <- function (object, signaling, slot.name = "netP", measure = c("outdeg", "indeg", "flowbet", "info"), measure.name = c("Sender", "Receiver", "Mediator", "Influencer"), color.use = NULL, color.heatmap = "BuGn", width = 6.5, height = 1.4, font.size = 8, font.size.title = 10, cluster.rows = FALSE, cluster.cols = FALSE) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_signalingRole_network", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netAnalysis_signalingRole_scatter`, with its original arguments.
#' @export
netAnalysis_signalingRole_scatter <- function (object, signaling = NULL, color.use = NULL, slot.name = "netP", group = NULL, weight.MinMax = NULL, dot.size = c(2, 6), point.shape = c(21, 22, 24, 23, 25, 8, 3), label.size = 3, dot.alpha = 0.6, x.measure = "outdeg", y.measure = "indeg", xlabel = "Outgoing interaction strength", ylabel = "Incoming interaction strength", title = NULL, font.size = 10, font.size.title = 10, do.label = T, show.legend = T, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netAnalysis_signalingRole_scatter", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netClustering`, with its original arguments.
#' @export
netClustering <- function (object, slot.name = "netP", type = c("functional", "structural"), comparison = NULL, k = NULL, methods = "kmeans", do.plot = TRUE, fig.id = NULL, do.parallel = TRUE, nCores = 4, k.eigen = NULL) {
  call <- match.call()
  call[[1L]] <- get("netClustering", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netEmbedding`, with its original arguments.
#' @export
netEmbedding <- function (object, slot.name = "netP", type = c("functional", "structural"), comparison = NULL, pathway.remove = NULL, umap.method = c("umap-learn", "uwot"), n_neighbors = NULL, min_dist = 0.3, ...) {
  call <- match.call()
  call[[1L]] <- get("netEmbedding", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netMappingDEG`, with its original arguments.
#' @export
netMappingDEG <- function (object, features.name, variable.all = TRUE, thresh = 0.05) {
  call <- match.call()
  call[[1L]] <- get("netMappingDEG", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual`, with its original arguments.
#' @export
netVisual <- function (object, signaling, signaling.name = NULL, color.use = NULL, vertex.receiver = NULL, sources.use = NULL, targets.use = NULL, top = 1, remove.isolate = FALSE, vertex.weight = 1, vertex.weight.max = NULL, vertex.size.max = NULL, weight.scale = TRUE, edge.weight.max.individual = NULL, edge.weight.max.aggregate = NULL, edge.width.max = 8, layout = c("circle", "hierarchy", "chord", "spatial"), height = 5, thresh = 0.05, pt.title = 12, title.space = 6, vertex.label.cex = 0.8, from = NULL, to = NULL,      bidirection = NULL, vertex.size = NULL, out.format = c("svg", "png"), sample.use = NULL, alpha.image = 0.15, point.size = 1.5, group = NULL, cell.order = NULL, small.gap = 1, big.gap = 10, scale = FALSE, reduce = -1, show.legend = FALSE, legend.pos.x = 20, legend.pos.y = 20, nCol = NULL, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_aggregate`, with its original arguments.
#' @export
netVisual_aggregate <- function (object, signaling, signaling.name = NULL, color.use = NULL, thresh = 0.05, vertex.receiver = NULL, sources.use = NULL, targets.use = NULL, idents.use = NULL, top = 1, remove.isolate = FALSE, vertex.weight = 1, vertex.weight.max = NULL, vertex.size.max = NULL, weight.scale = TRUE, edge.weight.max = NULL, edge.width.max = 8, layout = c("circle", "hierarchy", "chord", "spatial"), pt.title = 12, title.space = 6, vertex.label.cex = 0.8, sample.use = NULL, alpha.image = 0.15, point.size = 1.5,      group = NULL, cell.order = NULL, small.gap = 1, big.gap = 10, scale = FALSE, reduce = -1, show.legend = FALSE, legend.pos.x = 20, legend.pos.y = 20, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual_aggregate", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_barplot`, with its original arguments.
#' @export
netVisual_barplot <- function (object, comparison = c(1, 2), measure = c("count", "weight"), sources.use = NULL, targets.use = NULL, invert.source = FALSE, invert.target = FALSE, signaling = NULL, slot.name = c("netP", "net"), color.use = NULL, title.name = NULL, x.lab.rot = FALSE, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual_barplot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_bubble`, with its original arguments.
#' @export
netVisual_bubble <- function (object, sources.use = NULL, targets.use = NULL, signaling = NULL, pairLR.use = NULL, sort.by.source = FALSE, sort.by.target = FALSE, sort.by.source.priority = TRUE, color.heatmap = c("Spectral", "viridis"), n.colors = 10, direction = -1, thresh = 0.05, comparison = NULL, group = NULL, remove.isolate = FALSE, max.dataset = NULL, min.dataset = NULL, min.quantile = 0, max.quantile = 1, line.on = TRUE, line.size = 0.2, color.text.use = TRUE, color.text = NULL, dot.size.min = NULL, dot.size.max = NULL,      title.name = NULL, font.size = 10, font.size.title = 10, show.legend = TRUE, grid.on = TRUE, color.grid = "grey90", angle.x = 90, vjust.x = NULL, hjust.x = NULL, return.data = FALSE) {
  call <- match.call()
  call[[1L]] <- get("netVisual_bubble", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_chord_cell`, with its original arguments.
#' @export
netVisual_chord_cell <- function (object, signaling = NULL, net = NULL, slot.name = "netP", color.use = NULL, group = NULL, cell.order = NULL, sources.use = NULL, targets.use = NULL, lab.cex = 0.8, small.gap = 1, big.gap = 10, annotationTrackHeight = c(0.03), remove.isolate = FALSE, link.visible = TRUE, scale = FALSE, directional = 1, link.target.prop = TRUE, reduce = -1, transparency = 0.4, link.border = NA, title.name = NULL, show.legend = FALSE, legend.pos.x = 20, legend.pos.y = 20, nCol = NULL, thresh = 0.05, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual_chord_cell", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_chord_cell_internal`, with its original arguments.
#' @export
netVisual_chord_cell_internal <- function (net, color.use = NULL, group = NULL, cell.order = NULL, sources.use = NULL, targets.use = NULL, lab.cex = 0.8, small.gap = 1, big.gap = 10, annotationTrackHeight = c(0.03), remove.isolate = FALSE, link.visible = TRUE, scale = FALSE, directional = 1, link.target.prop = TRUE, reduce = -1, transparency = 0.4, link.border = NA, title.name = NULL, show.legend = FALSE, legend.pos.x = 20, legend.pos.y = 20, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual_chord_cell_internal", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_chord_gene`, with its original arguments.
#' @export
netVisual_chord_gene <- function (object, slot.name = "net", color.use = NULL, signaling = NULL, pairLR.use = NULL, net = NULL, sources.use = NULL, targets.use = NULL, lab.cex = 0.8, small.gap = 1, big.gap = 10, annotationTrackHeight = c(0.03), link.visible = TRUE, scale = FALSE, directional = 1, link.target.prop = TRUE, reduce = -1, transparency = 0.4, link.border = NA, title.name = NULL, legend.pos.x = 20, legend.pos.y = 20, show.legend = TRUE, thresh = 0.05, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual_chord_gene", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_circle`, with its original arguments.
#' @export
netVisual_circle <- function (net, color.use = NULL, title.name = NULL, sources.use = NULL, targets.use = NULL, idents.use = NULL, remove.isolate = FALSE, top = 1, weight.scale = FALSE, vertex.weight = 20, vertex.weight.max = NULL, vertex.size.max = NULL, vertex.label.cex = 1, vertex.label.color = "black", edge.weight.max = NULL, edge.width.max = 8, alpha.edge = 0.6, label.edge = FALSE, edge.label.color = "black", edge.label.cex = 0.8, edge.curved = 0.2, shape = "circle", layout = in_circle(), margin = 0.2, vertex.size = NULL,      arrow.width = 1, arrow.size = 0.2, text.x = 0, text.y = 1.5) {
  call <- match.call()
  call[[1L]] <- get("netVisual_circle", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_diffInteraction`, with its original arguments.
#' @export
netVisual_diffInteraction <- function (object, comparison = c(1, 2), measure = c("count", "weight", "count.merged", "weight.merged"), color.use = NULL, color.edge = c("#b2182b", "#2166ac"), title.name = NULL, sources.use = NULL, targets.use = NULL, remove.isolate = FALSE, top = 1, weight.scale = FALSE, vertex.weight = 20, vertex.weight.max = NULL, vertex.size.max = 15, vertex.label.cex = 1, vertex.label.color = "black", edge.weight.max = NULL, edge.width.max = 8, alpha.edge = 0.6, label.edge = FALSE, edge.label.color = "black",      edge.label.cex = 0.8, edge.curved = 0.2, shape = "circle", layout = in_circle(), margin = 0.2, arrow.width = 1, arrow.size = 0.2) {
  call <- match.call()
  call[[1L]] <- get("netVisual_diffInteraction", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_embedding`, with its original arguments.
#' @export
netVisual_embedding <- function (object, slot.name = "netP", type = c("functional", "structural"), color.use = NULL, pathway.labeled = NULL, top.label = 1, pathway.remove = NULL, pathway.remove.show = TRUE, dot.size = c(2, 6), label.size = 2, dot.alpha = 0.5, xlabel = "Dim 1", ylabel = "Dim 2", title = NULL, font.size = 10, font.size.title = 12, do.label = T, show.legend = T, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netVisual_embedding", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_embeddingPairwise`, with its original arguments.
#' @export
netVisual_embeddingPairwise <- function (object, slot.name = "netP", type = c("functional", "structural"), comparison = NULL, color.use = NULL, point.shape = NULL, pathway.labeled = NULL, top.label = 1, pathway.remove = NULL, pathway.remove.show = TRUE, dot.size = c(2, 6), label.size = 2.5, dot.alpha = 0.5, xlabel = "Dim 1", ylabel = "Dim 2", title = NULL, do.label = T, show.legend = T, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netVisual_embeddingPairwise", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_embeddingPairwiseZoomIn`, with its original arguments.
#' @export
netVisual_embeddingPairwiseZoomIn <- function (object, slot.name = "netP", type = c("functional", "structural"), comparison = NULL, color.use = NULL, nCol = 1, point.shape = NULL, pathway.remove = NULL, dot.size = c(2, 6), label.size = 2.8, dot.alpha = 0.5, xlabel = NULL, ylabel = NULL, do.label = T, show.legend = F, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netVisual_embeddingPairwiseZoomIn", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_embeddingZoomIn`, with its original arguments.
#' @export
netVisual_embeddingZoomIn <- function (object, slot.name = "netP", type = c("functional", "structural"), color.use = NULL, pathway.remove = NULL, nCol = 1, dot.size = c(2, 6), label.size = 2.8, dot.alpha = 0.5, xlabel = NULL, ylabel = NULL, do.label = T, show.legend = F, show.axes = T) {
  call <- match.call()
  call[[1L]] <- get("netVisual_embeddingZoomIn", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_heatmap`, with its original arguments.
#' @export
netVisual_heatmap <- function (object, comparison = c(1, 2), measure = c("count", "weight"), signaling = NULL, slot.name = c("netP", "net"), color.use = NULL, color.heatmap = NULL, title.name = NULL, width = NULL, height = NULL, ylim.top = NULL, ylim.right = NULL, font.size = 8, font.size.title = 10, cluster.rows = FALSE, cluster.cols = FALSE, sources.use = NULL, targets.use = NULL, remove.isolate = FALSE, row.show = NULL, col.show = NULL) {
  call <- match.call()
  call[[1L]] <- get("netVisual_heatmap", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_hierarchy1`, with its original arguments.
#' @export
netVisual_hierarchy1 <- function (net, vertex.receiver, color.use = NULL, title.name = NULL, sources.use = NULL, targets.use = NULL, remove.isolate = FALSE, top = 1, weight.scale = FALSE, vertex.weight = 20, vertex.weight.max = NULL, vertex.size.max = NULL, edge.weight.max = NULL, edge.width.max = 8, alpha.edge = 0.6, label.dist = 2.8, space.v = 1.5, space.h = 1.6, shape = NULL, label.edge = FALSE, edge.curved = 0, margin = 0.2, vertex.label.cex = 0.6, vertex.label.color = "black", arrow.width = 1, arrow.size = 0.2, edge.label.color = "black",      edge.label.cex = 0.5, vertex.size = NULL) {
  call <- match.call()
  call[[1L]] <- get("netVisual_hierarchy1", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_hierarchy2`, with its original arguments.
#' @export
netVisual_hierarchy2 <- function (net, vertex.receiver, color.use = NULL, title.name = NULL, sources.use = NULL, targets.use = NULL, remove.isolate = FALSE, top = 1, weight.scale = FALSE, vertex.weight = 20, vertex.weight.max = NULL, vertex.size.max = NULL, edge.weight.max = NULL, edge.width.max = 8, alpha.edge = 0.6, label.dist = 2.8, space.v = 1.5, space.h = 1.6, shape = NULL, label.edge = FALSE, edge.curved = 0, margin = 0.2, vertex.label.cex = 0.6, vertex.label.color = "black", arrow.width = 1, arrow.size = 0.2, edge.label.color = "black",      edge.label.cex = 0.5, vertex.size = NULL) {
  call <- match.call()
  call[[1L]] <- get("netVisual_hierarchy2", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_individual`, with its original arguments.
#' @export
netVisual_individual <- function (object, signaling, signaling.name = NULL, pairLR.use = NULL, color.use = NULL, vertex.receiver = NULL, sources.use = NULL, targets.use = NULL, top = 1, remove.isolate = FALSE, vertex.weight = 1, vertex.weight.max = NULL, vertex.size.max = NULL, vertex.label.cex = 0.8, weight.scale = TRUE, edge.weight.max = NULL, edge.width.max = 8, graphics.init = TRUE, layout = c("circle", "hierarchy", "chord", "spatial"), height = 5, thresh = 0.05, alpha.image = 0.15, point.size = 1.5, group = NULL, cell.order = NULL,      small.gap = 1, big.gap = 10, scale = FALSE, reduce = -1, show.legend = FALSE, legend.pos.x = 20, legend.pos.y = 20, nCol = NULL, ...) {
  call <- match.call()
  call[[1L]] <- get("netVisual_individual", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `netVisual_spatial`, with its original arguments.
#' @export
netVisual_spatial <- function (net, coordinates, meta, sample.use = NULL, color.use = NULL, title.name = NULL, sources.use = NULL, targets.use = NULL, idents.use = NULL, remove.isolate = FALSE, remove.loop = TRUE, top = 1, weight.scale = FALSE, vertex.weight = 20, vertex.weight.max = NULL, vertex.size.max = NULL, vertex.label.cex = 5, vertex.label.color = "black", edge.weight.max = NULL, edge.width.max = 8, edge.curved = 0.2, alpha.edge = 0.6, arrow.angle = 5, arrow.size = 0.2, alpha.image = 0.15, point.size = 1.5, legend.size = 5) {
  call <- match.call()
  call[[1L]] <- get("netVisual_spatial", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `normalizeData`, with its original arguments.
#' @export
normalizeData <- function (data.raw, scale.factor = 10000, do.log = TRUE, do.sparse = TRUE) {
  call <- match.call()
  call[[1L]] <- get("normalizeData", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `pieChart`, with its original arguments.
#' @export
pieChart <- function (df, label.size = 2.5, color.use = NULL, title = "") {
  call <- match.call()
  call[[1L]] <- get("pieChart", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `plotGeneExpression`, with its original arguments.
#' @export
plotGeneExpression <- function (object, features = NULL, signaling = NULL, enriched.only = TRUE, type = c("violin", "dot", "bar"), color.use = NULL, group.by = NULL, ...) {
  call <- match.call()
  call[[1L]] <- get("plotGeneExpression", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `preProcMultiomics`, with its original arguments.
#' @export
preProcMultiomics <- function (data.list, db, cutoff = 0.5, do.sparse = TRUE) {
  call <- match.call()
  call[[1L]] <- get("preProcMultiomics", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `rankSimilarity`, with its original arguments.
#' @export
rankSimilarity <- function (object, slot.name = "netP", type = c("functional", "structural"), comparison1 = NULL, comparison2 = c(1, 2), x.rotation = 90, title = NULL, color.use = NULL, bar.w = NULL, font.size = 8) {
  call <- match.call()
  call[[1L]] <- get("rankSimilarity", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `runCellChatApp`, with its original arguments.
#' @export
runCellChatApp <- function (object, ...) {
  call <- match.call()
  call[[1L]] <- get("runCellChatApp", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `runPCA`, with its original arguments.
#' @export
runPCA <- function (data.use, do.fast = T, dimPC = 50, seed.use = 42, weight.by.var = T) {
  call <- match.call()
  call[[1L]] <- get("runPCA", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `runUMAP`, with its original arguments.
#' @export
runUMAP <- function (data.use, n_neighbors = 30L, n_components = 2L, metric = "correlation", n_epochs = NULL, learning_rate = 1, min_dist = 0.3, spread = 1, set_op_mix_ratio = 1, local_connectivity = 1L, repulsion_strength = 1, negative_sample_rate = 5, a = NULL, b = NULL, seed.use = 42L, metric_kwds = NULL, angular_rp_forest = FALSE, verbose = FALSE) {
  call <- match.call()
  call[[1L]] <- get("runUMAP", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `scPalette`, with its original arguments.
#' @export
scPalette <- function (n) {
  call <- match.call()
  call[[1L]] <- get("scPalette", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `scaleData`, with its original arguments.
#' @export
scaleData <- function (data.use, do.center = T) {
  call <- match.call()
  call[[1L]] <- get("scaleData", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `scaleMat`, with its original arguments.
#' @export
scaleMat <- function (x, scale, na.rm = TRUE) {
  call <- match.call()
  call[[1L]] <- get("scaleMat", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `searchPair`, with its original arguments.
#' @export
searchPair <- function (signaling = c(), pairLR.use, key = c("pathway_name", "ligand"), matching.exact = FALSE, pair.only = TRUE) {
  call <- match.call()
  call[[1L]] <- get("searchPair", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `selectK`, with its original arguments.
#' @export
selectK <- function (object, slot.name = "netP", pattern = c("outgoing", "incoming"), title.name = NULL, do.facet = TRUE, k.range = seq(2, 10), nrun = 30, seed.use = 10) {
  call <- match.call()
  call[[1L]] <- get("selectK", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `setIdent`, with its original arguments.
#' @export
setIdent <- function (object, ident.use = NULL, levels = NULL, display.warning = TRUE) {
  call <- match.call()
  call[[1L]] <- get("setIdent", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `showDatabaseCategory`, with its original arguments.
#' @export
showDatabaseCategory <- function (CellChatDB, nrow = 1) {
  call <- match.call()
  call[[1L]] <- get("showDatabaseCategory", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `sketchData`, with its original arguments.
#' @export
sketchData <- function (object, percent, idents = NULL, do.PCA = TRUE, dimPC = 30) {
  call <- match.call()
  call[[1L]] <- get("sketchData", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `smoothData`, with its original arguments.
#' @export
smoothData <- function (object, method = c("netSmooth"), adj = NULL, alpha = 0.5, normalizeAdjMatrix = c("rows", "columns")) {
  call <- match.call()
  call[[1L]] <- get("smoothData", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `spatialDimPlot`, with its original arguments.
#' @export
spatialDimPlot <- function (object, color.use = NULL, group.by = NULL, sample.use = NULL, sources.use = NULL, targets.use = NULL, idents.use = NULL, alpha = 1, shape.by = 16, title.name = NULL, point.size = 2.4, legend.size = 5, legend.text.size = 8, legend.position = "right", ncol = 1, byrow = FALSE) {
  call <- match.call()
  call[[1L]] <- get("spatialDimPlot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `spatialFeaturePlot`, with its original arguments.
#' @export
spatialFeaturePlot <- function (object, features = NULL, signaling = NULL, pairLR.use = NULL, sample.use = NULL, enriched.only = TRUE, thresh = 0.05, do.group = TRUE, color.heatmap = "Spectral", n.colors = 8, direction = -1, do.binary = FALSE, cutoff = NULL, color.use = NULL, alpha = 1, point.size = 0.8, legend.size = 3, legend.text.size = 8, shape.by = 16, ncol = NULL, show.legend = TRUE, show.legend.combined = FALSE) {
  call <- match.call()
  call[[1L]] <- get("spatialFeaturePlot", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `subsetCellChat`, with its original arguments.
#' @export
subsetCellChat <- function (object, cells.use = NULL, idents.use = NULL, group.by = NULL, invert = FALSE, thresh = 0.05) {
  call <- match.call()
  call[[1L]] <- get("subsetCellChat", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `triMean`, with its original arguments.
#' @export
triMean <- function (x, na.rm = TRUE) {
  call <- match.call()
  call[[1L]] <- get("triMean", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `updateCCC_score`, with its original arguments.
#' @export
updateCCC_score <- function (object, net) {
  call <- match.call()
  call[[1L]] <- get("updateCCC_score", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `updateCellChat`, with its original arguments.
#' @export
updateCellChat <- function (object) {
  call <- match.call()
  call[[1L]] <- get("updateCellChat", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `updateCellChatDB`, with its original arguments.
#' @export
updateCellChatDB <- function (db, gene_info = NULL, other_info = NULL, gene_info_columnNew = NULL, trim.pathway = FALSE, merged = FALSE, species_target = NULL) {
  call <- match.call()
  call[[1L]] <- get("updateCellChatDB", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}

#' The pinned upstream `updateClusterLabels`, with its original arguments.
#' @export
updateClusterLabels <- function (object, old.cluster.name = NULL, new.cluster.name = NULL, new.order = NULL, new.cluster.metaname = "new.labels") {
  call <- match.call()
  call[[1L]] <- get("updateClusterLabels", envir = cellchatrs_upstream_cached())
  eval(call, envir = parent.frame())
}
