# Verbatim-upstream delegating wrappers: drop-in completeness for the computational surface.
#
# The shim ports the numeric kernel to Rust and overrides the functions it accelerates. Every other
# *computational* name upstream exports must still resolve, or `library(cellchatrs)` fails on the
# tutorial's third line. Each wrapper below calls the pinned upstream body verbatim (commit
# 75253cd0c9e68410e6e721a6d3a0419a1d7e358f) through `cellchatrs_upstream_cached()`, which sources the
# pinned files once per session.
#
# This is not the rankNetPairwise-fallback failure mode: nothing here claims to be a port. The docs
# say verbatim-upstream, the parity ledger records delegated names at the pass-through rung (never
# `exact`), and where a delegated function feeds a ported one the gates compare the ported output.
# Heavy-dependency callees (NMF/Seurat/IRLBA/presto-gated branches) fail exactly as upstream fails
# when the dependency is absent -- same body, same error -- because delegation evaluates nothing
# until called.
#
# Deliberately absent (locked decision PLAN.md 14.1 keeps visualization.R and app.R in R):
#
# - compareInteractions: returns a ggplot object; the numeric comparison workflow it fronts (mergeCellChat + rankNet comparison mode + rankNetPairwise) is ported and gated, and the tutorial covers the feeding slots.
# - netAnalysis_contribution: builds and returns a ggplot object.
# - netAnalysis_signalingRole_network: returns a ggplot object.
# - netVisual* / plotGeneExpression / dotPlot / barPlot / pieChart / spatial*Plot / StackedVlnPlot: visualization.R contents, locked decision 14.1.
# - netAnalysis_signalingRole_scatter/heatmap, river, dot, diffInteraction/scatter plots: visualization.R contents, locked decision 14.1.
# - scPalette/ggPalette/colorRamp3/CellChat_theme_opts: plot theming helpers, 14.1.
# - runCellChatApp: app.R Shiny application, 14.1.
#
# Generated by scripts/gen_delegate.py -- do not hand-edit; edit the table there and re-run.
# (Hand edits would be overwritten, which is the point: the export list must stay in sync with
# NAMESPACE and man/ by construction rather than by discipline.)


#' `createCellChat`, resolving to the documented upstream wrapper.
#'
#' Bare-name alias for `cellchatrs_upstream_createCellChat`: the constructor takes no numeric
#' arguments, so there is nothing to accelerate and the reference constructor is the constructor.
#' Upstream file: `R/CellChat_class.R`.
#' @export
createCellChat <- function(...) {
  cellchatrs_upstream_createCellChat(...)
}


#' The pinned upstream `setIdent`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
setIdent <- function(...) {
  get("setIdent", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `updateCellChat`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/CellChat_class.R`.
#' @export
updateCellChat <- function(...) {
  get("updateCellChat", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `subsetCellChat`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/CellChat_class.R`.
#' @export
subsetCellChat <- function(...) {
  get("subsetCellChat", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `updateClusterLabels`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
updateClusterLabels <- function(...) {
  get("updateClusterLabels", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `updateCCC_score`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
updateCCC_score <- function(...) {
  get("updateCCC_score", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `updateCellChatDB`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
updateCellChatDB <- function(...) {
  get("updateCellChatDB", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `showDatabaseCategory`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
showDatabaseCategory <- function(...) {
  get("showDatabaseCategory", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `checkGeneSymbol`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
checkGeneSymbol <- function(...) {
  get("checkGeneSymbol", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `addMeta`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
addMeta <- function(...) {
  get("addMeta", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `addReduction`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
addReduction <- function(...) {
  get("addReduction", envir = cellchatrs_upstream_cached())(...)
}


#' `mergeCellChat`, resolving to the documented upstream wrapper.
#'
#' Bare-name alias for `cellchatrs_upstream_mergeCellChat`, so there is exactly one code path and
#' one documented rung (pass-through; see tests/parity/check_merge.R). Upstream file:
#' `R/CellChat_class.R`.
#' @export
mergeCellChat <- function(...) {
  cellchatrs_upstream_mergeCellChat(...)
}


#' The pinned upstream `computeExpr_LR`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExpr_LR <- function(...) {
  get("computeExpr_LR", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeExpr_complex`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExpr_complex <- function(...) {
  get("computeExpr_complex", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeExpr_coreceptor`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExpr_coreceptor <- function(...) {
  get("computeExpr_coreceptor", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeExpr_agonist`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExpr_agonist <- function(...) {
  get("computeExpr_agonist", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeExpr_antagonist`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExpr_antagonist <- function(...) {
  get("computeExpr_antagonist", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeExprGroup_agonist`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExprGroup_agonist <- function(...) {
  get("computeExprGroup_agonist", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeExprGroup_antagonist`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
computeExprGroup_antagonist <- function(...) {
  get("computeExprGroup_antagonist", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `triMean`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
triMean <- function(...) {
  get("triMean", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `geometricMean`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`.
#' @export
geometricMean <- function(...) {
  get("geometricMean", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `extractGene`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
extractGene <- function(...) {
  get("extractGene", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `extractGeneSubset`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
extractGeneSubset <- function(...) {
  get("extractGeneSubset", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `extractGeneSubsetFromPair`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
extractGeneSubsetFromPair <- function(...) {
  get("extractGeneSubsetFromPair", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `extractLRfromGenes`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
extractLRfromGenes <- function(...) {
  get("extractLRfromGenes", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `extractEnrichedLR`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
extractEnrichedLR <- function(...) {
  get("extractEnrichedLR", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `findEnrichedSignaling`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
findEnrichedSignaling <- function(...) {
  get("findEnrichedSignaling", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `identifyEnrichedInteractions`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/modeling.R`. Downstream of the ported filterCommunication; the enrichment statistic itself is a rank test over the interaction table.
#' @export
identifyEnrichedInteractions <- function(...) {
  get("identifyEnrichedInteractions", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `identifyOverExpressedInteractions`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`. Pure set-membership filtering over the DB tables; no floating point, no randomness. Covered end-to-end by the tutorial reproduction, which routes the tutorial's own call through here.
#' @export
identifyOverExpressedInteractions <- function(...) {
  get("identifyOverExpressedInteractions", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `identifyOverExpressedLigandReceptor`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
identifyOverExpressedLigandReceptor <- function(...) {
  get("identifyOverExpressedLigandReceptor", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `mergeInteractions`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
mergeInteractions <- function(...) {
  get("mergeInteractions", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `searchPair`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/database.R`.
#' @export
searchPair <- function(...) {
  get("searchPair", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `getMaxWeight`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
getMaxWeight <- function(...) {
  get("getMaxWeight", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `normalizeData`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
normalizeData <- function(...) {
  get("normalizeData", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `scaleData`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
scaleData <- function(...) {
  get("scaleData", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `scaleMat`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
scaleMat <- function(...) {
  get("scaleMat", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `smoothData`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`.
#' @export
smoothData <- function(...) {
  get("smoothData", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `sketchData`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`. Needs Seurat at call time, exactly as upstream does.
#' @export
sketchData <- function(...) {
  get("sketchData", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `selectK`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
selectK <- function(...) {
  get("selectK", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeEnrichmentScore`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
computeEnrichmentScore <- function(...) {
  get("computeEnrichmentScore", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeNetD_structure`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
computeNetD_structure <- function(...) {
  get("computeNetD_structure", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeNetSimilarity`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
computeNetSimilarity <- function(...) {
  get("computeNetSimilarity", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeNetSimilarityPairwise`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
computeNetSimilarityPairwise <- function(...) {
  get("computeNetSimilarityPairwise", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `rankSimilarity`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
rankSimilarity <- function(...) {
  get("rankSimilarity", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `liftCellChat`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/CellChat_class.R`.
#' @export
liftCellChat <- function(...) {
  get("liftCellChat", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `identifyCommunicationPatterns`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`. Needs NMF at call time, exactly as upstream does.
#' @export
identifyCommunicationPatterns <- function(...) {
  get("identifyCommunicationPatterns", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `netClustering`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`. Needs NMF/IRLBA at call time, exactly as upstream does.
#' @export
netClustering <- function(...) {
  get("netClustering", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `netEmbedding`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`. Needs Seurat/IRLBA at call time, exactly as upstream does.
#' @export
netEmbedding <- function(...) {
  get("netEmbedding", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `netMappingDEG`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
netMappingDEG <- function(...) {
  get("netMappingDEG", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeLaplacian`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
computeLaplacian <- function(...) {
  get("computeLaplacian", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `computeEigengap`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`.
#' @export
computeEigengap <- function(...) {
  get("computeEigengap", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `buildSNN`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/analysis.R`. Needs Seurat at call time, exactly as upstream does.
#' @export
buildSNN <- function(...) {
  get("buildSNN", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `runPCA`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`. Needs Seurat at call time, exactly as upstream does.
#' @export
runPCA <- function(...) {
  get("runPCA", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `runUMAP`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`. Needs Seurat at call time, exactly as upstream does.
#' @export
runUMAP <- function(...) {
  get("runUMAP", envir = cellchatrs_upstream_cached())(...)
}


#' The pinned upstream `preProcMultiomics`, verbatim.
#'
#' Drop-in delegation: resolves the name for `library(cellchatrs)` users by calling the pinned
#' upstream body (see the header of this file for what delegation does and does not claim).
#' Upstream file: `R/utilities.R`. Needs Seurat/Signac at call time, exactly as upstream does.
#' @export
preProcMultiomics <- function(...) {
  get("preProcMultiomics", envir = cellchatrs_upstream_cached())(...)
}

